# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /opt/concourse/volumes/live/f31aa560-b365-403e-5b37-700f316b1f59/volume/rsync-recipes/lzo-2.10-on-osx, last modified Wed Nov 15 22:09:11 2017
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '2'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: h362108e_2
requirements:
    build:
        - bzip2 1.0.6 h649919c_2
        - ca-certificates 2017.08.26 ha1e5d58_0
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h6c06975_3
        - cmake 3.9.4 h30c3106_0
        - compiler-rt 4.0.1 h5487866_0
        - curl 7.55.1 h2e228d0_4
        - expat 2.2.5 hb8e80ba_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libssh2 1.8.0 h1218725_2
        - libuv 1.14.0 h740c2a5_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - ncurses 6.0 hd04f020_2
        - openssl 1.0.2m h86d3e6a_1
        - rhash 1.3.5 h3aa0507_1
        - xz 5.2.3 h0278029_2
        - zlib 1.2.11 hf3cbc9b_2
test:
    commands:
        - test -f ${PREFIX}/include/lzo/lzoconf.h
        - test -f ${PREFIX}/lib/liblzo2.a
        - test -f ${PREFIX}/lib/liblzo2.dylib
        - conda inspect linkages -p $PREFIX lzo
        - conda inspect objects -p $PREFIX lzo
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
