# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/066fba6a-62ab-434c-4e8c-770464006161/volume/rsync-recipes/pytest-astropy-0.5.0-python_3.7-on-osx, last modified Mon Dec 17 12:35:07 2018
# ------------------------------------------------

package:
    name: pytest-astropy
    version: 0.5.0
source:
    fn: pytest-astropy-0.5.0.tar.gz
    sha256: 6f28fb81dcdfa745f423b8f6d0303d97357d775b4128bcc2b3668f1602fd5a0b
    url: https://pypi.io/packages/source/p/pytest-astropy/pytest-astropy-0.5.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - pytest >=3.1
        - pytest-arraydiff >=0.1
        - pytest-doctestplus >=0.2.0
        - pytest-openfiles >=0.3.1
        - pytest-remotedata >=0.3.1
        - python >=3.7,<3.8.0a0
test:
    imports:
        - pytest_arraydiff
        - pytest_doctestplus
        - pytest_openfiles
        - pytest_remotedata
about:
    description: 'This is a meta-package that pulls in the dependencies that are used
        by

        astropy and some affiliated packages for testing. It can also be used for

        testing packages that are not affiliated with the Astropy project.

        '
    dev_url: https://github.com/astropy/pytest-astropy
    doc_url: https://github.com/astropy/pytest-astropy
    home: https://github.com/astropy/pytest-astropy
    license: BSD
    summary: Meta-package containing dependencies for testing Astropy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - drdavella
        - mwcraig
