# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/isort-feedstock/recipe, last modified Tue Apr 17 13:35:58 2018
# ------------------------------------------------

package:
    name: isort
    version: 4.3.4
source:
    fn: isort-4.3.4.tar.gz
    sha256: b9c40e9750f3d77e6e4d441d8b0266cf555e7cdabdcff33c4fd06366ca761ef8
    url: https://pypi.io/packages/source/i/isort/isort-4.3.4.tar.gz
build:
    entry_points:
        - isort = isort.main:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - isort --help
    imports:
        - isort
about:
    description: 'isort is a Python utility / library to sort imports alphabetically,
        and

        automatically separated into sections. It provides a command line utility,

        Python library and plugins for various editors to quickly sort all your

        imports. It currently cleanly supports Python 2.6 - 3.5 using pies to

        achieve this without ugly hacks and/or py2to3.

        '
    dev_url: https://github.com/timothycrosley/isort
    doc_source_url: https://github.com/timothycrosley/isort/blob/develop/README.rst
    doc_url: http://isort.readthedocs.io/en/latest/
    home: https://github.com/timothycrosley/isort
    license: MIT
    license_file: LICENSE
    summary: A Python utility / library to sort Python imports.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - nehaljwani
        - nicoddemus
