# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/345386c8-69ba-47df-77cc-2e963c40f23d/volume/rsync-recipes/xlrd-1.2.0-python_3.7-on-osx, last modified Mon Dec 17 14:36:38 2018
# ------------------------------------------------

package:
    name: xlrd
    version: 1.2.0
source:
    sha256: 546eb36cee8db40c3eaa46c351e67ffee6eeb5fa2650b71bc4c758a29a1b29b2
    url: https://pypi.io/packages/source/x/xlrd/xlrd-1.2.0.tar.gz
build:
    noarch: false
    number: '0'
    script: /opt/concourse/worker/volumes/live/345386c8-69ba-47df-77cc-2e963c40f23d/volume/xlrd_1545084513567/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps -vv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
test:
    files:
        - test.xlsx
about:
    description: 'xlrd is a library for reading data and formatting information from
        Excel files,

        whether they are .xls or .xlsx files.

        '
    dev_url: https://github.com/python-excel/xlrd/
    doc_source_url: https://github.com/python-excel/xlrd/blob/master/docs/index.rst
    doc_url: http://xlrd.readthedocs.io/en/latest/
    home: http://www.python-excel.org/
    license: BSD 3-Clause and BSD with advertising
    license_family: BSD
    license_file: LICENSE
    summary: Library for developers to extract data from Microsoft Excel (tm) spreadsheet
        files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - cokelaer
