# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/77f17423-9b17-4602-561b-a998ddd8e48d/volume/rsync-recipes/prometheus_client-0.5.0-python_3.7-on-osx, last modified Mon Dec 17 11:57:25 2018
# ------------------------------------------------

package:
    name: prometheus_client
    version: 0.5.0
source:
    sha256: 2d7f7af343dec0a96ee849b1bba18aad9f767bf16d5eb5f0c11cae837bf22731
    url: https://github.com/prometheus/client_python/archive/v0.5.0.tar.gz
build:
    noarch: false
    number: '0'
    script: /opt/concourse/worker/volumes/live/77f17423-9b17-4602-561b-a998ddd8e48d/volume/prometheus_client_1545082434671/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - prometheus_client
        - prometheus_client.bridge
about:
    home: https://github.com/prometheus/client_python
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Python client for the Prometheus monitoring system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jessicaaustin
        - kwilcox
        - ocefpaf
