# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/9c8dd744-846d-4a74-5c55-4d5b63aa2291/volume/rsync-recipes/mpmath-1.1.0-python_3.7-on-osx, last modified Mon Dec 17 11:57:15 2018
# ------------------------------------------------

package:
    name: mpmath
    version: 1.1.0
source:
    fn: mpmath-1.1.0.tar.gz
    sha256: fc17abe05fbab3382b61a123c398508183406fa132e0223874578e20946499f6
    url: https://pypi.io/packages/source/m/mpmath/mpmath-1.1.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - mpmath
        - mpmath.calculus
        - mpmath.functions
        - mpmath.libmp
        - mpmath.matrices
        - mpmath.tests
about:
    description: 'mpmath is a free Python library for real and complex floating-point

        arithmetic with arbitrary precision.

        '
    dev_url: https://github.com/fredrik-johansson/mpmath
    doc_source_url: https://github.com/fredrik-johansson/mpmath/blob/master/doc/source/index.txt
    doc_url: http://mpmath.org/doc/current/
    home: http://mpmath.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Python library for arbitrary-precision floating-point arithmetic
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - msarahan
        - ocefpaf
