# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/dbaf7ab3-f1c4-431c-7248-925bd2429fcf/volume/rsync-recipes/msgpack-python-0.5.6-python_3.7-on-osx, last modified Fri Aug  3 14:41:20 2018
# ------------------------------------------------

package:
    name: msgpack-python
    version: 0.5.6
source:
    fn: msgpack-python-0.5.6.tar.gz
    sha256: 0ee8c8c85aa651be3aa0cd005b5931769eaa658c948ce79428766f1bd46ae2c3
    url: https://pypi.io/packages/source/m/msgpack/msgpack-0.5.6.tar.gz
build:
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37h04f5b5a_1
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - cython 0.28.4 py37h0a44026_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h1de35cc_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libcxx >=4.0.1
        - python >=3.7,<3.8.0a0
test:
    imports:
        - msgpack
about:
    description: 'MessagePack lets you exchange data among multiple languages like
        JSON.  But

        it is faster and smaller. Small integers are encoded into a single byte and

        typical short strings require only one extra byte in addition to the

        strings themselves.

        '
    dev_url: https://github.com/msgpack/msgpack
    doc_source_url: https://github.com/msgpack/msgpack-python/blob/master/docs/index.rst
    doc_url: http://msgpack-python.readthedocs.io/
    home: http://msgpack.org/
    license: Apache 2.0
    license_family: Apache
    license_file: COPYING
    summary: MessagePack (de)serializer.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pmlandwehr
