# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/sip-feedstock/recipe, last modified Tue Apr 17 13:42:54 2018
# ------------------------------------------------

package:
    name: sip
    version: 4.19.8
source:
    patches:
        - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch
    sha256: 7eaf7a2ea7d4d38a56dd6d2506574464bddf7cf284c960801679942377c297bc
    url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.19.8/sip-4.19.8.tar.gz
build:
    number: '0'
    string: py37h0a44026_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libcxx >=4.0.1
        - python >=3.7,<3.8.0a0
test:
    files:
        - test
    imports:
        - sip
    requires:
        - clangxx_osx-64
about:
    description: 'SIP is a tool that makes it very easy to create Python bindings
        for C and

        C++ libraries. SIP comprises a code generator and a Python module. The

        code generator processes a set of specification files and generates C or

        C++ code which is then compiled to create the bindings extension module.

        The SIP Python module provides support functions to the automatically

        generated code.

        '
    dev_url: https://github.com/ifwe/sip
    doc_url: http://pyqt.sourceforge.net/Docs/sip4/
    home: http://www.riverbankcomputing.com/software/sip/intro
    license: GPL-3.0
    license_file: LICENSE
    summary: Create Python bindings for C and C++ libraries
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - msarahan
        - ocefpaf
