# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/jinja2-feedstock/recipe, last modified Tue Apr 17 13:36:12 2018
# ------------------------------------------------

package:
    name: jinja2
    version: '2.10'
source:
    fn: Jinja2-2.10.tar.gz
    sha256: f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4
    url: https://pypi.io/packages/source/J/Jinja2/Jinja2-2.10.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - markupsafe >=0.23
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    imports:
        - jinja2
about:
    description: 'Jinja2 is a full featured template engine for Python. It has full
        unicode

        support, an optional integrated sandboxed execution environment, widely

        used and BSD licensed.

        '
    dev_url: https://github.com/pallets/jinja
    doc_source_url: https://github.com/pallets/jinja/blob/master/docs/index.rst
    doc_url: http://jinja.pocoo.org/docs/dev/
    home: http://jinja.pocoo.org
    license: 3-Clause BSD
    license_file: LICENSE
    summary: An easy to use stand-alone template engine written in pure python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - nehaljwani
        - scopatz
