# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f3f9c8c5-2efb-4843-77f7-81ca7bb03453/volume/rsync-recipes/atomicwrites-1.2.1-python_3.7-on-osx, last modified Tue Sep  4 13:29:57 2018
# ------------------------------------------------

package:
    name: atomicwrites
    version: 1.2.1
source:
    fn: atomicwrites-1.2.1.tar.gz
    sha256: ec9ae8adaae229e4f8446952d204a3e4b5fdd2d099f9be3aaf556120135fb3ee
    url: https://pypi.io/packages/source/a/atomicwrites/atomicwrites-1.2.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - atomicwrites
about:
    dev_url: https://github.com/untitaker/python-atomicwrites
    home: https://github.com/untitaker/python-atomicwrites
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Atomic file writes.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nicoddemus
        - tadeu
