# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/d2c436d2-e40f-4bd4-6ecc-940c82065b2c/volume/rsync-recipes/scikit-learn-0.20.1-blas_impl_mkl-python_3.7-on-osx, last modified Fri Dec 14 13:42:16 2018
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.20.1
source:
    fn: scikit-learn-0.20.1.tar.gz
    patches:
        - 0001-reduce-precision-of-almost_equal-in-test_graph_lasso.patch
    sha256: 618feea121c59a52ea459d6af7bc179344ca345775b04bd60e96740e9df75960
    url: https://github.com/scikit-learn/scikit-learn/archive/0.20.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37h27c97d8_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - cython 0.29 py37h0a44026_0
        - intel-openmp 2019.1 144
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.1 144
        - mkl-devel 2019.1 144
        - mkl-include 2019.1 144
        - ncurses 6.1 h0a44026_1
        - numpy-base 1.11.3 py37h6575580_12
        - numpy-devel 1.11.3 py37h4ba5984_12
        - openssl 1.1.1a h1de35cc_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - libcxx >=4.0.1
        - mkl >=2019.1,<2020.0a0
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - scipy
test:
    commands:
        - pytest --showlocals --durations=20 --pyargs sklearn
    imports:
        - sklearn
    requires:
        - pytest
about:
    home: http://scikit-learn.org/
    license: BSD 3-Clause
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - amueller
        - astaric
        - jakirkham
        - lesteve
        - msarahan
        - ocefpaf
        - ogrisel
