# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/45a7e724-55df-4267-448f-0b79a4dfc3ab/volume/rsync-recipes/multipledispatch-0.6.0-python_3.7-on-osx, last modified Tue Aug 14 11:25:49 2018
# ------------------------------------------------

package:
    name: multipledispatch
    version: 0.6.0
source:
    fn: multipledispatch-0.6.0.tar.gz
    sha256: a7ab1451fd0bf9b92cab3edbd7b205622fb767aeefb4fb536c2e3de9e0a38bea
    url: https://pypi.io/packages/source/m/multipledispatch/multipledispatch-0.6.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/45a7e724-55df-4267-448f-0b79a4dfc3ab/volume/multipledispatch_1534268863364/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.13 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 40.0.0 py37_0
        - six 1.11.0 py37_1
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - multipledispatch
about:
    description: 'This implementation of multiple dispatch is efficient, mostly complete,

        performs static analysis to avoid conflicts, and provides optional

        namespace support.

        '
    dev_url: https://github.com/mrocklin/multipledispatch/
    doc_source_url: https://github.com/mrocklin/multipledispatch/blob/master/docs/source/index.rst
    doc_url: https://multiple-dispatch.readthedocs.io
    home: https://github.com/mrocklin/multipledispatch/
    license: BSD 3-Clause
    license_family: BSD
    summary: Multiple dispatch in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
