# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/datashape-feedstock/recipe, last modified Thu Jun 28 14:10:19 2018
# ------------------------------------------------

package:
    name: datashape
    version: 0.5.4
source:
    fn: datashape-0.5.4.tar.gz
    sha256: c266c5803dde48b9fa8d8ee51b5b5979ef77443060e32db2d225b72648c638a5
    url: https://github.com/blaze/datashape/archive/0.5.4.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_1
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - multipledispatch >=0.4.7
        - numpy >=1.7
        - python >=3.7,<3.8.0a0
        - python-dateutil
test:
    commands:
        - py.test -vx --doctest-modules --pyargs datashape
    imports:
        - datashape
        - datashape.tests
        - datashape.util
    requires:
        - mock
        - numpy 1.11.*
        - pytest
about:
    description: 'Datashape is a data layout language for array programming.

        It is designed to describe in-situ structured data without requiring

        transformation into a canonical form.

        '
    dev_url: https://github.com/blaze/datashape
    doc_source_url: https://github.com/blaze/datashape/blob/master/docs/source/index.rst
    doc_url: http://datashape.readthedocs.org/en/latest
    home: http://datashape.pydata.org
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A data description language.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
