# This file created by conda-build 3.8.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/aee2c8e2-9944-4f91-7f0e-80e0dee0b32d/volume/rsync-recipes/ca-certificates-2018.03.07-on-osx, last modified Mon Apr  2 14:13:34 2018
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2018.03.07
source:
    fn: cacert.pem
    sha256: 79ea479e9f329de7075c40154c591b51eb056d458bc4dff76d9a4b9c6c4f6d0b
    url: https://curl.haxx.se/ca/cacert-2018-03-07.pem
build:
    commands:
        - /usr/bin/curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
        - /usr/bin/openssl -CAfile "${PREFIX}/ssl/cacert.pem" -CApath nosuchdir s_client
            -showcerts -connect www.google.com:443
        - test -f "${PREFIX}/ssl/cacert.pem"
        - test -f "${PREFIX}/ssl/cert.pem"
    string: '0'
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
