# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/heapdict-feedstock/recipe, last modified Tue Apr 17 13:35:26 2018
# ------------------------------------------------

package:
    name: heapdict
    version: 1.0.0
source:
    fn: heapdict-1.0.0.tar.gz
    sha256: 4c8e581f1651ca78da35820fc80b0d50fc060032517f2c7efd9169e204db3793
    url: https://github.com/DanielStutzbach/heapdict/archive/v1.0.0.tar.gz
build:
    number: '2'
    script: python setup.py install
    string: py37_2
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - heapdict
about:
    description: 'heapdict implements the MutableMapping ABC, meaning it works pretty
        much

        like a regular Python dict. It''s designed to be used as a priority queue.

        '
    dev_url: https://github.com/DanielStutzbach/heapdict
    doc_source_url: https://github.com/DanielStutzbach/heapdict/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/HeapDict
    home: http://stutzbachenterprises.com/
    license: BSD 3-Clause
    license_file: LICENSE
    summary: A heap with decrease-key and increase-key operations
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mrocklin
        - ocefpaf
