# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/entrypoints-feedstock/recipe, last modified Tue Apr 17 13:34:02 2018
# ------------------------------------------------

package:
    name: entrypoints
    version: 0.2.3
source:
    fn: entrypoints-0.2.3.tar.gz
    sha256: d2d587dde06f99545fb13a383d2cd336a8ff1f359c5839ce3a64c917d10c029f
    url: https://pypi.io/packages/source/e/entrypoints/entrypoints-0.2.3.tar.gz
build:
    number: '2'
    script: python setup.py install
    string: py37_2
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
about:
    description: 'Entry points are a way for Python packages to advertise objects
        with

        some common interface. The most common examples are console_scripts

        entry points, which define shell commands by identifying a Python

        function to run

        '
    dev_url: https://github.com/takluyver/entrypoints
    doc_source_url: https://github.com/takluyver/entrypoints/tree/master/doc
    doc_url: https://entrypoints.readthedocs.io/en/latest/
    home: https://github.com/takluyver/entrypoints
    license: MIT License
    license_family: MIT
    license_file: LICENSE
    summary: Discover and load entry points from installed packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - minrk
        - ocefpaf
        - pelson
        - takluyver
