# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/backports-feedstock/recipe, last modified Wed Sep 20 04:39:34 2017
# ------------------------------------------------

package:
    name: backports
    version: '1.0'
build:
    number: '1'
    string: py37_1
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - backports
about:
    description: 'Namespace for backported Python features.

        '
    doc_source_url: https://bitbucket.org/brandon/backports/src/931d2c348a93313413e444c0724db7ac5030a496/setup.py?at=default&fileviewer=file-view-default
    doc_url: https://pypi.python.org/pypi/backports/
    home: https://bitbucket.org/brandon/backports
    license: BSD
extra:
    copy_test_source_files: true
    final: true
