# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/9356797d-f1c2-405e-508f-064019d41c5a/volume/rsync-recipes/openpyxl-2.5.12-python_3.7-on-osx, last modified Mon Dec 17 11:57:03 2018
# ------------------------------------------------

package:
    name: openpyxl
    version: 2.5.12
source:
    fn: openpyxl-2.5.12.tar.gz
    sha256: 7bcf019a0be528673a8aec1e60b5c863342c3231962dbf7922fd4da42a49a91a
    url: https://pypi.io/packages/source/o/openpyxl/openpyxl-2.5.12.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - et_xmlfile
        - jdcal
        - python >=3.7,<3.8.0a0
test:
    imports:
        - openpyxl
        - openpyxl.cell
        - openpyxl.chart
        - openpyxl.chartsheet
        - openpyxl.comments
        - openpyxl.compat
        - openpyxl.descriptors
        - openpyxl.drawing
        - openpyxl.formatting
        - openpyxl.formula
        - openpyxl.packaging
        - openpyxl.reader
        - openpyxl.styles
        - openpyxl.utils
        - openpyxl.workbook
        - openpyxl.workbook.external_link
        - openpyxl.worksheet
        - openpyxl.writer
        - openpyxl.xml
about:
    description: 'openpyxl is a Python library to read/write Excel 2010

        xlsx/xlsm/xltx/xltm files.

        '
    dev_url: https://bitbucket.org/openpyxl/openpyxl/
    doc_source_url: https://bitbucket.org/openpyxl/openpyxl/src/default/doc/index.rst
    doc_url: https://openpyxl.readthedocs.io/
    home: https://openpyxl.readthedocs.io
    license: MIT
    license_family: MIT
    license_file: LICENCE.rst
    summary: A Python library to read/write Excel 2010 xlsx/xlsm files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - curtisalexander
