# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/gmpy2-feedstock/recipe, last modified Mon Jun 18 07:02:00 2018
# ------------------------------------------------

package:
    name: gmpy2
    version: 2.0.8
source:
    fn: gmpy2-2.0.8.zip
    sha256: dd233e3288b90f21b0bb384bcc7a7e73557bb112ccf0032ad52aa614eb373d3f
    url: https://pypi.io/packages/source/g/gmpy2/gmpy2-2.0.8.zip
build:
    number: '2'
    script:
        - python setup.py install --shared=$PREFIX
    string: py37h6ef4df4_2
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - gmp 6.1.2 hb37e062_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - mpc 1.1.0 h6ef4df4_1
        - mpfr 4.0.1 h3018a27_3
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - gmp >=6.1.2
        - mpc
        - mpfr >=4.0.1,<5.0a0
        - python >=3.7,<3.8.0a0
test:
    imports:
        - gmpy2
about:
    home: https://pypi.python.org/pypi/gmpy2
    license: LGPL 3
    license_file: COPYING.LESSER
    summary: GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
