# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/8fc4f1d6-2288-441f-715d-b7e84bfd151a/volume/rsync-recipes/alabaster-0.7.12-python_3.7-on-osx, last modified Mon Oct  8 12:46:06 2018
# ------------------------------------------------

package:
    name: alabaster
    version: 0.7.12
source:
    sha256: a661d72d58e6ea8a57f7a86e37d86716863ee5e92788398526d58b26a4e4dc02
    url: https://pypi.io/packages/source/a/alabaster/alabaster-0.7.12.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.4.3 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.0 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - python -c "import alabaster; print(alabaster.get_path())"
    imports:
        - alabaster
about:
    description: 'Alabaster is a visually clean, responsive, and configurable Sphinx

        theme. It is sidebar-enabled and easy to install/use as a Python

        package. As of Sphinx 1.3, Alabaster is selected as the default

        theme for Sphinx.

        '
    dev_url: https://github.com/bitprophet/alabaster
    doc_url: https://anaconda.org/anaconda/alabaster
    home: http://www.sphinx-doc.org/en/stable/index.html
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Configurable, Python 2+3 compatible Sphinx theme.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - r-jain1
