# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/15b8ea55-0e66-47c7-5ff3-b73e1ad91d02/volume/rsync-recipes/sqlite-3.26.0-on-osx, last modified Mon Dec 17 08:37:42 2018
# ------------------------------------------------

package:
    name: sqlite
    version: 3.26.0
source:
    fn: sqlite-autoconf-3260000.tar.gz
    sha1: 9af2df1a6da5db6e2ecf3f463625f16740e036e9
    url: https://www.sqlite.org/2018/sqlite-autoconf-3260000.tar.gz
build:
    number: '0'
    run_exports:
        - sqlite >=3.26.0,<4.0a0
    string: ha441bb4_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - make 4.2.1 h3efe00b_1
    commands:
        - sqlite3 --version
    host:
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - ncurses 6.1 h0a44026_1
        - zlib 1.2.11 h1de35cc_3
    run:
        - libedit >=3.1.20170329,<3.2.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
