# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/0f3c8485-c6b5-4d9f-71f9-63f2a70a6982/volume/rsync-recipes/pytest-doctestplus-0.2.0-python_3.7-on-osx, last modified Fri Nov 16 09:30:51 2018
# ------------------------------------------------

package:
    name: pytest-doctestplus
    version: 0.2.0
source:
    fn: pytest-doctestplus-0.2.0.tar.gz
    sha256: f18fe570201e5e8182cbc50a5db7b9b3185faaee9da1635dc1e36296660e9b5a
    url: https://pypi.io/packages/source/p/pytest-doctestplus/pytest-doctestplus-0.2.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.1.1 h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.5.0 py37_0
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.2 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - numpy >=1.10
        - pytest >=2.8
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - pytest_doctestplus
about:
    description: 'This package contains a plugin for the pytest framework that provides

        advanced doctest support and enables the testing of reStructuredText files.

        '
    dev_url: https://github.com/astropy/pytest-doctestplus
    doc_url: https://github.com/astropy/pytest-doctestplus
    home: https://github.com/astropy/pytest-doctestplus
    license: BSD
    summary: Pytest plugin with advanced doctest features
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - drdavella
        - mwcraig
