# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/727ec5b6-fa19-48ae-513e-3410ddd32d03/volume/rsync-recipes/pytest-remotedata-0.3.1-python_3.7-on-osx, last modified Tue Oct 30 21:48:19 2018
# ------------------------------------------------

package:
    name: pytest-remotedata
    version: 0.3.1
source:
    fn: pytest-remotedata-0.3.1.tar.gz
    sha256: 15b75a38431da96a4da5e48b20a18e4dcc40d191abc199b17cb969f818530481
    url: https://pypi.io/packages/source/p/pytest-remotedata/pytest-remotedata-0.3.1.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.1.1 h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.4.3 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.2 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - pytest >=3.1
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - pytest_remotedata
about:
    description: 'This package provides a plugin for the pytest framework that allows

        developers to control unit tests that require access to data from the

        internet.

        '
    dev_url: https://github.com/astropy/pytest-remotedata
    doc_url: https://github.com/astropy/pytest-remotedata
    home: https://github.com/astropy/pytest-remotedata
    license: BSD
    summary: Pytest plugin for controlling remote data access
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - drdavella
        - mwcraig
