# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a9ef74a7-2465-4c84-584d-d9b766aa9347/volume/rsync-recipes/anaconda-client-1.7.2-python_3.7-on-osx, last modified Wed Aug 29 14:12:00 2018
# ------------------------------------------------

package:
    name: anaconda-client
    version: 1.7.2
source:
    git_rev: 1.7.2
    git_url: https://github.com/Anaconda-Platform/anaconda-client.git
build:
    entry_points:
        - anaconda = binstar_client.scripts.cli:main
    string: py37_0
requirements:
    host:
        - asn1crypto 0.24.0 py37_0
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - cffi 1.11.5 py37h6174b99_1
        - chardet 3.0.4 py37_1
        - clyent 1.2.2 py37_1
        - cryptography 2.3.1 py37hdbc3d79_0
        - decorator 4.3.0 py37_0
        - idna 2.7 py37_0
        - ipython_genutils 0.2.0 py37_0
        - jsonschema 2.6.0 py37_0
        - jupyter_core 4.4.0 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - nbformat 4.4.0 py37_0
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pycparser 2.18 py37_1
        - pyopenssl 18.0.0 py37_0
        - pysocks 1.6.8 py37_0
        - python 3.7.0 hc167b69_0
        - python-dateutil 2.7.3 py37_0
        - pytz 2018.5 py37_0
        - pyyaml 3.13 py37h1de35cc_0
        - readline 7.0 h1de35cc_5
        - requests 2.19.1 py37_0
        - setuptools 40.2.0 py37_0
        - six 1.11.0 py37_1
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - traitlets 4.3.2 py37_0
        - urllib3 1.23 py37_0
        - xz 5.2.4 h1de35cc_4
        - yaml 0.1.7 hc338f04_2
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - clyent >=1.2.2
        - nbformat
        - python >=3.7,<3.8.0a0
        - python-dateutil
        - pytz
        - pyyaml
        - requests >=2.9.1
        - setuptools
test:
    commands:
        - anaconda -h
        - anaconda --version
    imports:
        - binstar_client
        - binstar_client.scripts.cli
    requires:
        - conda
about:
    description: 'Anaconda-client is used to connect to and manage your Anaconda Cloud
        account, upload packages you have created

        and generate access tokens to allow access to private packages.

        '
    dev_url: https://github.com/Anaconda-Platform/anaconda-client
    doc_source_url: https://github.com/Anaconda-Platform/anaconda-client/blob/develop/README.md
    doc_url: https://docs.continuum.io/anaconda-cloud/cli
    home: http://anaconda.org
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE.md
    summary: anaconda.org command line client library
extra:
    copy_test_source_files: true
    final: true
