# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/terminado-feedstock/recipe, last modified Tue Apr 17 13:43:32 2018
# ------------------------------------------------

package:
    name: terminado
    version: 0.8.1
source:
    sha256: 55abf9ade563b8f9be1f34e4233c7b7bde726059947a593322e8a553cc4c067a
    url: https://pypi.io/packages/source/t/terminado/terminado-0.8.1.tar.gz
build:
    number: '1'
    script: python setup.py install
    string: py37_1
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - ptyprocess
        - python >=3.7,<3.8.0a0
        - tornado >=4
test:
    imports:
        - terminado
    requires:
        - nose
about:
    description: 'Terminado is a Tornado websocket backend for the term.js Javascript

        terminal emulator library.

        '
    dev_url: https://github.com/takluyver/terminado
    doc_source_url: https://github.com/takluyver/terminado/blob/master/doc/index.rst
    doc_url: http://terminado.readthedocs.org/en/latest/
    home: https://github.com/jupyter/terminado
    license: BSD 2-clause
    summary: Terminals served by tornado websockets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pelson
        - takluyver
