# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/odo-feedstock/recipe, last modified Mon Sep 11 14:08:54 2017
# ------------------------------------------------

package:
    name: odo
    version: 0.5.1
source:
    fn: odo-0.5.1.tar.gz
    sha256: e3ae46d57bfb4430eba0dfe1f13911fc91f1d9e76d6d364b908b24eb9a604fa9
    url: https://github.com/blaze/odo/archive/0.5.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - dask >=0.11.1
        - datashape >=0.5.0
        - multipledispatch >=0.4.7
        - networkx >=1.0
        - numpy >=1.7
        - pandas >=0.15.0
        - python >=3.7,<3.8.0a0
        - toolz >=0.7.3
test:
    imports:
        - odo
        - odo.backends
        - odo.backends.tests
        - odo.tests
about:
    description: 'Odo is data migration for the Blaze Project. t efficiently migrates
        data

        from the source to the target through a network of conversions.

        '
    dev_url: https://github.com/blaze/odo
    doc_source_url: https://github.com/blaze/odo/blob/master/docs/source/index.rst
    doc_url: http://odo.readthedocs.org/en/latest/
    home: http://odo.pydata.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Data migration in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
