# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/d3cb48a6-16a6-4391-6ad2-06fc150499f9/volume/rsync-recipes/itsdangerous-1.1.0-python_3.7-on-osx, last modified Wed Oct 31 17:23:57 2018
# ------------------------------------------------

package:
    name: itsdangerous
    version: 1.1.0
source:
    fn: itsdangerous-1.1.0.tar.gz
    sha256: 321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19
    url: https://pypi.io/packages/source/i/itsdangerous/itsdangerous-1.1.0.tar.gz
build:
    noarch: false
    number: '0'
    script: /opt/concourse/worker/volumes/live/d3cb48a6-16a6-4391-6ad2-06fc150499f9/volume/itsdangerous_1541025457533/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.1.1 h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.4.3 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.2 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - itsdangerous
about:
    description: 'Internally itsdangerous uses HMAC and SHA1 for signing data and
        bases the

        implementation on the Django signing module.  It also however supports JSON
        Web

        Signatures (JWS).

        '
    dev_url: https://github.com/pallets/itsdangerous
    doc_source_url: https://github.com/pallets/itsdangerous/blob/master/docs/index.rst
    doc_url: http://pythonhosted.org/itsdangerous
    home: https://github.com/pallets/itsdangerous
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.rst
    summary: Various helpers to pass trusted data to untrusted environments.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - nicoddemus
        - williamjamir
