# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/decorator-feedstock/recipe, last modified Tue Apr 17 13:33:52 2018
# ------------------------------------------------

package:
    name: decorator
    version: 4.3.0
source:
    fn: decorator-4.3.0.tar.gz
    sha256: c39efa13fbdeb4506c476c9b3babf6a718da943dab7811c206005a4a956c080c
    url: https://pypi.io/packages/source/d/decorator/decorator-4.3.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - decorator
about:
    description: 'Preserve the signature of decorated functions in a consistent way

        across Python releases.

        '
    dev_url: https://github.com/micheles/decorator
    doc_source_url: https://github.com/micheles/decorator/tree/master/docs
    doc_url: http://decorator.readthedocs.io/en/stable/
    home: https://github.com/micheles/decorator
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Better living through Python with decorators.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
