# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/67609a1a-4023-49f3-472c-178b8aff6445/volume/rsync-recipes/glib-2.56.2-on-osx, last modified Tue Aug 28 11:50:55 2018
# ------------------------------------------------

package:
    name: glib
    version: 2.56.2
source:
    fn: glib-2.56.2.tar.xz
    patches:
        - 0001-F_SETPIPE_SZ-absence-workaround.patch
        - 0001-Revert-Stop-using-ptrctl-for-thread-names.patch
        - hardcoded-paths.patch
    sha256: d64abd16813501c956c4e123ae79f47f1b58de573df9fdd3b0795f1e2c1aa789
    url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.56/glib-2.56.2.tar.xz
build:
    detect_binary_files_with_prefix: true
    missing_dso_whitelist:
        - /usr/lib/libresolv.9.dylib
    number: '0'
    run_exports:
        - glib >=2.56.2,<2.57.0a0
    string: hd9629dc_0
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.15.1 pl526h2ca55ef_0
        - ca-certificates 2018.03.07 0
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libiconv 1.15 hdd342a3_7
        - libtool 2.4.6 hdb3952c_3
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - perl 5.26.2 h4e221da_0
        - pkg-config 0.29.2 h3efe00b_8
        - python 3.5.5 h0a44026_3
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    host:
        - gettext 0.19.8.1 h15daf44_3
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libffi 3.2.1 h475c297_4
        - libiconv 1.15 hdd342a3_7
        - pcre 8.42 h378b8a2_0
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - gettext >=0.19.8.1,<1.0a0
        - libcxx >=4.0.1
        - libffi >=3.2.1,<4.0a0
        - libiconv >=1.15,<2.0a0
        - pcre >=8.42,<9.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libglib-2.0.dylib
about:
    description: 'GLib provides the core application building blocks for libraries
        and

        applications written in C. It provides the core object system used in

        GNOME, the main loop implementation, and a large set of utility functions

        functions for strings and common data structures.

        '
    dev_url: https://git.gnome.org/browse/glib/
    doc_source_url: https://git.gnome.org/browse/glib/tree/docs
    doc_url: https://developer.gnome.org/glib/unstable/
    home: https://developer.gnome.org/glib/
    license: LGPL-2.1
    summary: Provides core application building blocks for libraries and applications
        written in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - pkgw
        - scopatz
