# This file created by conda-build 3.16.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/19d6c310-0aa8-4212-7f02-8109b90bcd62/volume/rsync-recipes/libssh2-1.8.0-on-osx, last modified Thu Oct 25 14:04:19 2018
# ------------------------------------------------

package:
    name: libssh2
    version: 1.8.0
source:
    fn: libssh2-1.8.0.tar.gz
    sha256: 39f34e2f6835f4b992cafe8625073a88e5a28ba78f83e8099610a7b3af4676d4
    url: https://www.libssh2.org/download/libssh2-1.8.0.tar.gz
build:
    number: '4'
    run_exports:
        - libssh2 >=1.8.0,<2.0a0
    string: ha12b0ac_4
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - cmake-binary 3.9.1 h19c0166_1
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - make 4.2.1 h3efe00b_1
    host:
        - ca-certificates 2018.03.07 0
        - openssl 1.1.1 h1de35cc_0
    run:
        - openssl >=1.1.1,<1.1.2.0a0
test:
    commands:
        - test -f $PREFIX/include/libssh2.h
        - test -f $PREFIX/include/libssh2_publickey.h
        - test -f $PREFIX/include/libssh2_sftp.h
        - test -f $PREFIX/lib/libssh2.a
        - test -f $PREFIX/lib/libssh2.dylib
about:
    description: 'libssh2 is a library implementing the SSH2 protocol, available under
        the revised BSD license.

        '
    dev_url: https://github.com/libssh2/libssh2
    home: https://www.libssh2.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: the SSH library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - shadowwalkersb
