# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f6613cca-0688-409c-5452-28e7ab400f1a/volume/rsync-recipes/rope-0.11.0-python_3.7-on-osx, last modified Mon Aug 13 10:35:44 2018
# ------------------------------------------------

package:
    name: rope
    version: 0.11.0
source:
    sha256: a108c445e1cd897fe19272ab7877d172e7faf3d4148c80e7d20faba42ea8f7b2
    url: https://pypi.io/packages/source/r/rope/rope-0.11.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/f6613cca-0688-409c-5452-28e7ab400f1a/volume/rope_1534177309734/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h1de35cc_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 40.0.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - rope
        - rope.base
        - rope.base.oi
        - rope.base.oi.type_hinting
        - rope.base.oi.type_hinting.providers
        - rope.base.oi.type_hinting.resolvers
        - rope.base.utils
        - rope.contrib
        - rope.refactor
        - rope.refactor.importutils
about:
    dev_url: https://github.com/python-rope/rope
    doc_source_url: https://github.com/python-rope/rope/tree/master/docs
    doc_url: https://pypi.python.org/pypi/rope
    home: https://github.com/python-rope/rope
    license: GPL 2.0
    license_family: GPL2
    license_file: COPYING
    summary: A python refactoring library...
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
