# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/fb9d8740-2a80-4877-6fac-d3b443879001/volume/rsync-recipes/pywavelets-1.0.1-python_3.7-on-osx, last modified Wed Oct  3 15:45:40 2018
# ------------------------------------------------

package:
    name: pywavelets
    version: 1.0.1
source:
    fn: PyWavelets-1.0.1.tar.gz
    sha256: 8d3eead94a3426d59444f3b63660d89ea5a9bad49f0b4a9aad3adc4cb75fbfc2
    url: https://github.com/PyWavelets/pywt/archive/v1.0.1.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/fb9d8740-2a80-4877-6fac-d3b443879001/volume/pywavelets_1538600523279/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed -vvv
    string: py37h1d22016_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - cython 0.28.5 py37h0a44026_0
        - intel-openmp 2019.0 118
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.0 118
        - ncurses 6.1 h0a44026_0
        - numpy 1.11.3 py37h6a91979_10
        - numpy-base 1.11.3 py37h8a80b8c_10
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
test:
    import:
        - pywt
    requires:
        - nose
about:
    description: 'PyWavelets is a free Open Source library for wavelet transforms
        in Python.

        Wavelets are mathematical basis functions that are localized in both time
        and frequency.

        Wavelet transforms are time-frequency transforms employing wavelets. They
        are similar to

        Fourier transforms, the difference being that Fourier transforms are localized
        only in

        frequency instead of in time and frequency.

        '
    dev_url: https://github.com/PyWavelets/pywt
    doc_source_url: https://github.com/PyWavelets/pywt/tree/master/doc
    doc_url: http://pywavelets.readthedocs.io/en/latest/
    home: https://github.com/PyWavelets/pywt
    license: MIT
    license_file: LICENSE
    summary: Discrete Wavelet Transforms in Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - grlee77
        - jakirkham
        - ocefpaf
