# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/c793f6f7-436a-468a-4dc3-9a45da62fe90/volume/rsync-recipes/pandas-0.23.4-python_3.7-on-osx, last modified Tue Aug  7 12:55:56 2018
# ------------------------------------------------

package:
    name: pandas
    version: 0.23.4
source:
    sha256: 5b24ca47acf69222e82530e89111dd9d14f9b970ab2cd3a1c2c78f0c4fbba4f4
    url: https://github.com/pandas-dev/pandas/releases/download/v0.23.4/pandas-0.23.4.tar.gz
build:
    number: '0'
    string: py37h6440ff4_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - cython 0.28.4 py37h0a44026_0
        - intel-openmp 2018.0.3 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2018.0.3 1
        - ncurses 6.1 h0a44026_0
        - numpy 1.11.3 py37h648b28d_9
        - numpy-base 1.11.3 py37h8a80b8c_9
        - openssl 1.0.2o h1de35cc_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libcxx >=4.0.1
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.5.*
        - pytz
test:
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD 3-clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - jorisvandenbossche
        - jreback
        - msarahan
        - ocefpaf
