# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/e43e9ba6-edb4-412f-4ac4-2c753b6f866a/volume/rsync-recipes/python-libarchive-c-2.8-python_3.7-on-osx, last modified Sun Sep 30 05:44:05 2018
# ------------------------------------------------

package:
    name: python-libarchive-c
    version: '2.8'
source:
    fn: python-libarchive-c-2.8.tar.gz
    patches:
        - 0001-Add-zstd-support.patch
        - 0002-Export-ArchiveWrite.patch
    sha256: 06d44d5b9520bdac93048c72b7ed66d11a6626da16d2086f9aad079674d8e061
    url: https://pypi.io/packages/source/l/libarchive-c/libarchive-c-2.8.tar.gz
build:
    number: '6'
    string: py37_6
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libarchive
        - python >=3.7,<3.8.0a0
test:
    imports:
        - libarchive
about:
    home: https://github.com/Changaco/python-libarchive-c
    license: CC0-1.0
    summary: Python interface to libarchive
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - mingwandroid
