# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/1b06b262-1fa7-45ee-4f05-3218019e6c51/volume/rsync-recipes/python.app-2-python_3.7-on-osx, last modified Thu Sep 27 02:02:45 2018
# ------------------------------------------------

package:
    name: python.app
    version: '2'
build:
    number: '9'
    string: py37_9
requirements:
    build:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - python.app -V
        - pythonw -V
    files:
        - t.py
about:
    license: BSD
    summary: Proxy on OS X letting Python libraries hook into the gui event loop
extra:
    copy_test_source_files: true
    final: true
