# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f19107e9-1c10-45cf-5458-0374fcc6687e/volume/rsync-recipes/pathlib2-2.3.3-python_3.7-on-osx, last modified Mon Dec 17 11:57:01 2018
# ------------------------------------------------

package:
    name: pathlib2
    version: 2.3.3
source:
    fn: pathlib2-2.3.3.tar.gz
    sha256: 25199318e8cc3c25dcb45cbe084cc061051336d5a9ea2a12448d3d8cb748f742
    url: https://pypi.io/packages/source/p/pathlib2/pathlib2-2.3.3.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - pathlib2
about:
    description: 'The goal of pathlib2 is to provide a backport of standard pathlib
        module which

        tracks the standard library module, so all the newest features of the standard

        pathlib can be used also on older Python versions.

        '
    doc_source_url: https://github.com/mcmtroffaes/pathlib2/blob/develop/README.rst
    doc_url: https://pypi.python.org/pypi/pathlib2/
    home: https://github.com/mcmtroffaes/pathlib2
    license: MIT
    license_file: LICENSE.rst
    summary: Fork of pathlib aiming to support the full stdlib Python API.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pelson
        - takluyver
