# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f00484c5-2175-4ec8-4f9b-f23b5e208029/volume/rsync-recipes/spyder-3.3.2-python_3.7-on-osx, last modified Wed Nov 28 15:10:42 2018
# ------------------------------------------------

package:
    name: spyder
    version: 3.3.2
source:
    patches:
        - osx-zmq.patch
    sha256: ab3a30321d3142bf6c98f71cea3a6d65b4b6f67d4b77c4966249e8547bb9bbfa
    url: https://pypi.io/packages/source/s/spyder/spyder-3.3.2.tar.gz
build:
    entry_points:
        - spyder = spyder.app.start:main
    number: '0'
    osx_is_app: true
    string: py37_0
requirements:
    host:
        - alabaster 0.7.12 py37_0
        - asn1crypto 0.24.0 py37_0
        - babel 2.6.0 py37_0
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - cffi 1.11.5 py37h6174b99_1
        - chardet 3.0.4 py37_1
        - cryptography 2.4.1 py37ha12b0ac_0
        - docutils 0.14 py37_0
        - idna 2.7 py37_0
        - imagesize 1.1.0 py37_0
        - jinja2 2.10 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - markupsafe 1.1.0 py37h1de35cc_0
        - ncurses 6.1 h0a44026_0
        - openssl 1.1.1a h1de35cc_0
        - packaging 18.0 py37_0
        - pip 18.1 py37_0
        - pycparser 2.19 py37_0
        - pygments 2.2.0 py37_0
        - pyopenssl 18.0.0 py37_0
        - pyparsing 2.3.0 py37_0
        - pysocks 1.6.8 py37_0
        - python 3.7.1 haf84260_3
        - pytz 2018.7 py37_0
        - readline 7.0 h1de35cc_5
        - requests 2.20.1 py37_0
        - setuptools 40.6.2 py37_0
        - six 1.11.0 py37_1
        - snowballstemmer 1.2.1 py37_0
        - sphinx 1.8.2 py37_0
        - sphinxcontrib 1.0 py37_1
        - sphinxcontrib-websupport 1.1.0 py37_1
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - urllib3 1.23 py37_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - chardet >=2.0
        - cloudpickle
        - jedi >=0.9
        - keyring
        - nbconvert
        - numpydoc
        - pickleshare
        - psutil
        - pycodestyle
        - pyflakes
        - pygments >=2.0
        - pylint
        - pyqt 5.*
        - python >=3.7,<3.8.0a0
        - python.app
        - pyzmq
        - qtawesome >=0.4.1
        - qtconsole >=4.2
        - qtpy >=1.5.0
        - rope >=0.10.5
        - sphinx
        - spyder-kernels >=0.1,<1
test:
    commands:
        - USER=test spyder -h
    imports:
        - spyder
app:
    entry: spyder
    icon: logo.png
    summary: The Scientific Python Development Environment
    type: desk
about:
    description: 'Spyder is a powerful scientific environment written in Python, for
        Python,

        and designed by and for scientists, engineers and data analysts.

        It features a unique combination of the advanced editing, analysis,

        debugging and profiling functionality of a comprehensive development tool

        with the data exploration, interactive execution, deep inspection and

        beautiful visualization capabilities of a scientific package.\n

        Furthermore, Spyder offers built-in integration with many popular

        scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,

        Matplotlib, SymPy, and more.\n

        Beyond its many built-in features, Spyder can be extended even further via

        third-party plugins.\n

        Spyder can also be used as a PyQt5 extension library, allowing you to build

        upon its functionality and embed its components, such as the interactive

        console or advanced editor, in your own software.

        '
    dev_url: https://github.com/spyder-ide/spyder
    doc_url: https://docs.spyder-ide.org/
    home: https://www.spyder-ide.org/
    license: MIT
    license_file: LICENSE.txt
    summary: The Scientific Python Development Environment
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - goanpeca
