# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/pytables-feedstock/recipe, last modified Thu Jun 28 14:11:23 2018
# ------------------------------------------------

package:
    name: pytables
    version: 3.4.4
source:
    fn: pytables-3.4.4.tar.gz
    patches:
        - noavx2.patch
    sha256: c9682c0f35d8175e12bbd38d925bdb606d47b7c8e358ba056a9dbf3b1f183114
    url: https://github.com/PyTables/PyTables/archive/v3.4.4.tar.gz
build:
    entry_points:
        - pt2to3 = tables.scripts.pt2to3:main
        - ptdump = tables.scripts.ptdump:main
        - ptrepack = tables.scripts.ptrepack:main
        - pttree = tables.scripts.pttree:main
    number: '0'
    string: py37h13cba08_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - blas 1.0 mkl
        - blosc 1.14.3 hd9629dc_0
        - bzip2 1.0.6 h1de35cc_5
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - cython 0.28.3 py37h1de35cc_0
        - hdf5 1.10.2 hfa1e0ec_1
        - intel-openmp 2018.0.3 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - lzo 2.10 h362108e_2
        - mkl 2018.0.3 1
        - ncurses 6.1 h0a44026_0
        - numexpr 2.6.5 py37hf9f1f73_0
        - numpy 1.11.3 py37heee0a97_5
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - snappy 1.1.7 he62c110_3
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - blosc >=1.14.3,<2.0a0
        - bzip2 >=1.0.6,<2.0a0
        - hdf5 >=1.10.2,<1.10.3.0a0
        - libcxx >=4.0.1
        - lzo >=2.10,<3.0a0
        - numexpr
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - six
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pt2to3 -h
        - ptdump -h
        - ptrepack -h
        - pttree -h
    requires:
        - mock
        - setuptools
about:
    description: 'PyTables is a package for managing hierarchical datasets and designed
        to

        efficiently and easily cope with extremely large amounts of data. PyTables

        is built on top of the HDF5 library, using the Python language and the

        NumPy package.

        '
    dev_url: https://github.com/PyTables
    doc_url: http://www.pytables.org/
    home: http://www.pytables.org
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Brings together Python, HDF5 and NumPy to easily handle large amounts
        of data.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - msarahan
        - ocefpaf
        - scopatz
        - tomkooij
