# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/9e7f76dd-93f5-4db2-76c3-a49aefeda5a9/volume/rsync-recipes/sympy-1.3-python_3.7-on-osx, last modified Fri Sep 28 12:12:44 2018
# ------------------------------------------------

package:
    name: sympy
    version: '1.3'
source:
    fn: sympy-1.3.tar.gz
    md5: 11e18423f52e248108a3bd4307185bc1
    url: https://pypi.io/packages/source/s/sympy/sympy-1.3.tar.gz
build:
    noarch: false
    number: '0'
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - fastcache 1.0.2 py37h1de35cc_2
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - mpmath 1.0.0 py37_2
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - fastcache
        - gmpy2 >=2.0.8
        - mpmath >=0.19
        - python >=3.7,<3.8.0a0
test:
    commands:
        - isympy --help
    imports:
        - sympy
about:
    description: 'SymPy is a Python library for symbolic mathematics. It aims to become
        a

        full-featured computer algebra system (CAS) while keeping the code as

        simple as possible in order to be comprehensible and easily extensible.

        '
    dev_url: https://github.com/sympy/sympy
    doc_url: http://docs.sympy.org/latest/index.html
    home: http://sympy.org
    license: 3-clause BSD
    license_family: BSD
    license_file: LICENSE
    summary: Python library for symbolic mathematics
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - msarahan
        - scopatz
