# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/55a52cce-66fe-43b3-6bc8-fd438de290cb/volume/rsync-recipes/path.py-11.5.0-python_3.7-on-osx, last modified Mon Oct 15 13:56:38 2018
# ------------------------------------------------

package:
    name: path.py
    version: 11.5.0
source:
    fn: path.py-11.5.0.tar.gz
    sha256: b6687a532a735a2d79a13e92bdb31cb0971abe936ea0fa78bcb47faf4372b3cb
    url: https://pypi.io/packages/source/p/path.py/path.py-11.5.0.tar.gz
build:
    noarch: false
    number: '0'
    script: /opt/concourse/worker/volumes/live/55a52cce-66fe-43b3-6bc8-fd438de290cb/volume/path.py_1539703918737/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.4.3 py37_0
        - setuptools_scm 3.1.0 py37h28b3542_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - backports.os
        - importlib_metadata >=0.5
        - python >=3.7,<3.8.0a0
test:
    imports:
        - path
about:
    description: 'path.py implements a path objects as first-class entities, allowing
        common

        operations on files to be invoked on those path objects directly.

        '
    dev_url: https://github.com/jaraco/path.py
    doc_source_url: https://github.com/jaraco/path.py/blob/master/docs/index.rst
    doc_url: https://pathpy.readthedocs.io/en/latest/
    home: https://github.com/jaraco/path.py
    license: MIT
    license_file: LICENSE
    summary: A module wrapper for os.path
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
