# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/5233df37-f420-41e3-71d3-ca7938d3baf4/volume/rsync-recipes/distributed-1.25.1-python_3.7-on-osx, last modified Mon Dec 17 11:56:57 2018
# ------------------------------------------------

package:
    name: distributed
    version: 1.25.1
source:
    sha256: 8f226e14953736ea8c51e7da2a33d0f5974a0a5e0778c82b3513e85e15495ee1
    url: https://pypi.io/packages/source/d/distributed/distributed-1.25.1.tar.gz
build:
    entry_points:
        - dask-mpi=distributed.cli.dask_mpi:go
        - dask-remote=distributed.cli.dask_remote:go
        - dask-scheduler=distributed.cli.dask_scheduler:go
        - dask-ssh=distributed.cli.dask_ssh:go
        - dask-submit=distributed.cli.dask_submit:go
        - dask-worker=distributed.cli.dask_worker:go
    number: '0'
    script: /opt/concourse/worker/volumes/live/5233df37-f420-41e3-71d3-ca7938d3baf4/volume/distributed_1545075000536/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - click >=6.6
        - cloudpickle >=0.2.2
        - cytoolz >=0.7.4
        - dask-core >=0.18.0
        - msgpack-python
        - psutil >=5.0
        - python >=3.7,<3.8.0a0
        - pyyaml
        - six
        - sortedcontainers !=2.0.0,!=2.0.1
        - tblib
        - toolz >=0.7.4
        - tornado >=4.5.1
        - zict >=0.1.3
test:
    commands:
        - dask-scheduler --help
        - dask-ssh --help
        - dask-worker --help
    imports:
        - distributed
        - distributed.cli
        - distributed.comm
        - distributed.deploy
        - distributed.diagnostics
        - distributed.protocol
about:
    description: 'Distributed is a lightweight library for distributed computing in
        Python.

        It extends both the concurrent.futures and dask APIs to moderate sized

        clusters.

        '
    dev_url: https://github.com/dask/distributed
    doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
    doc_url: http://distributed.readthedocs.org
    home: http://distributed.readthedocs.io/en/latest/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Distributed computing with Dask
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - marcelotrevisani
        - martindurant
        - mrocklin
        - pitrou
