# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/4a63d576-4ee5-4b1b-7877-8b1618bae2d1/volume/rsync-recipes/pyzmq-17.1.2-python_3.7-on-osx, last modified Tue Aug 14 12:13:16 2018
# ------------------------------------------------

package:
    name: pyzmq
    version: 17.1.2
source:
    fn: pyzmq-17.1.2.tar.gz
    sha256: a72b82ac1910f2cf61a49139f4974f994984475f771b0faa730839607eeedddf
    url: https://pypi.io/packages/source/p/pyzmq/pyzmq-17.1.2.tar.gz
build:
    number: '0'
    string: py37h1de35cc_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.13 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libiconv 1.15 hdd342a3_7
        - libsodium 1.0.16 h3efe00b_0
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - pkg-config 0.29.2 h3efe00b_8
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 40.0.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zeromq 4.2.5 h0a44026_0
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libsodium >=1.0.16,<1.0.17.0a0
        - python >=3.7,<3.8.0a0
        - zeromq >=4.2.5,<4.2.6.0a0
test:
    commands:
        - py.test --pyargs zmq.tests.test_socket
    imports:
        - zmq
        - zmq.backend.cython.socket
        - zmq.backend.cython.utils
        - zmq.devices.monitoredqueue
    requires:
        - pytest
about:
    description: 'PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and
        fast

        messaging implementation.

        '
    dev_url: https://github.com/zeromq/pyzmq
    doc_source_url: https://github.com/zeromq/pyzmq/blob/master/docs/source/index.rst
    doc_url: https://pyzmq.readthedocs.org/
    home: https://github.com/zeromq/pyzmq
    license: BSD 3-clause
    license_family: BSD
    summary: Python bindings for zeromq
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - minrk
        - msarahan
        - pelson
