# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/1d850d7c-73e2-4704-759a-4baacbb676d8/volume/rsync-recipes/gettext-0.19.8.1-on-osx, last modified Mon Nov 13 15:40:27 2017
# ------------------------------------------------

package:
    name: gettext
    version: 0.19.8.1
source:
    fn: gettext-0.19.8.1.tar.xz
    sha256: 105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4
    url: ftp://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz
build:
    number: '3'
    run_exports:
        - gettext >=0.19.8.1,<1.0a0
    string: h15daf44_3
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h6c06975_3
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libffi 3.2.1 h475c297_4
        - libiconv 1.15 hdd342a3_7
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    run:
        - libffi >=3.2.1,<4.0a0
        - libiconv >=1.15,<2.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libintl.dylib
about:
    home: https://www.gnu.org/software/gettext/
    license: GPLv2
    license_file: COPYING
    summary: Internationalization package.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
