# This file created by conda-build 3.8.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/4b7445f9-9639-4163-5bf3-eaaf30b88b5d/volume/rsync-recipes/pcre-8.42-on-osx, last modified Fri Apr 13 08:27:02 2018
# ------------------------------------------------

package:
    name: pcre
    version: '8.42'
source:
    fn: pcre-8.42.tar.gz
    patches:
        - 0001-Define-snprintf-for-old-VS.patch
        - 0002-Workaround-CMake-FIND_PACKAGE-ZLIB-looking-on-PATH-misfeature.patch
    sha256: 69acbc2fbdefb955d42a4c606dfde800c2885711d2979e356c0636efde9ec3b5
    url: ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.42.tar.gz
build:
    number: '0'
    run_exports:
        - pcre >=8.42,<9.0a0
    string: h378b8a2_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_10
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_10
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libiconv 1.15 hdd342a3_7
        - libtool 2.4.6 hdb3952c_3
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - pkg-config 0.29.2 h3efe00b_8
    host:
        - bzip2 1.0.6 hd86a083_4
        - ca-certificates 2018.03.07 0
        - cmake 3.9.4 h30c3106_0
        - curl 7.59.0 ha441bb4_0
        - expat 2.2.5 hb8e80ba_0
        - libcurl 7.59.0 hf30b1f0_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libssh2 1.8.0 h322a93b_4
        - libuv 1.19.2 hfd94794_0
        - ncurses 6.0 hd04f020_2
        - openssl 1.0.2o h26aff7b_0
        - rhash 1.3.5 h3aa0507_1
        - xz 5.2.3 h0278029_2
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libcxx >=4.0.1
test:
    commands:
        - pcre-config --version
        - pcregrep --help
        - pcretest --help
        - test -f "${PREFIX}/include/pcre.h"
        - test -f "${PREFIX}/include/pcre_scanner.h"
        - test -f "${PREFIX}/include/pcre_stringpiece.h"
        - test -f "${PREFIX}/include/pcrecpp.h"
        - test -f "${PREFIX}/include/pcrecpparg.h"
        - test -f "${PREFIX}/include/pcreposix.h"
        - test -f "${PREFIX}/lib/libpcre.a"
        - test -f "${PREFIX}/lib/libpcre.dylib"
        - test -f "${PREFIX}/lib/libpcrecpp.a"
        - test -f "${PREFIX}/lib/libpcrecpp.dylib"
        - test -f "${PREFIX}/lib/libpcreposix.a"
        - test -f "${PREFIX}/lib/libpcreposix.dylib"
about:
    description: 'PCRE implement regular expression pattern matching using the same
        syntax and

        semantics as Perl 5. PCRE has its own native API, as well as a set of wrapper

        functions that correspond to the POSIX regular expression API.

        '
    dev_url: http://vcs.pcre.org/pcre2/
    doc_source_url: https://vcs.pcre.org/pcre2/code/trunk/doc/?sortdir=down
    doc_url: http://www.pcre.org/original/doc/html/
    home: http://www.pcre.org/
    license: BSD 3-Clause
    license_family: BSD
    summary: Regular expression pattern matching using the same syntax and semantics
        as Perl 5.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - scopatz
        - sebastian-luna-valero
