# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/h5py-feedstock/recipe, last modified Wed Aug 22 06:36:38 2018
# ------------------------------------------------

package:
    name: h5py
    version: 2.8.0
source:
    fn: h5py-2.8.0.tar.gz
    sha256: eae41382be28b7264824450ce343dd625f972bedaaa3b0cced284986aabcbaee
    url: https://github.com/h5py/h5py/archive/2.8.0.tar.gz
build:
    number: '3'
    string: py37h878fce3_3
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.13 py37_0
        - cython 0.28.5 py37h0a44026_0
        - hdf5 1.10.2 hfa1e0ec_1
        - intel-openmp 2018.0.3 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - libiconv 1.15 hdd342a3_7
        - mkl 2018.0.3 1
        - ncurses 6.1 h0a44026_0
        - numpy-base 1.11.3 py37h1bbf6aa_9
        - numpy-devel 1.11.3 py37h99ba2d1_9
        - openssl 1.0.2p h1de35cc_0
        - pkg-config 0.29.2 h3efe00b_8
        - pkgconfig 1.3.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 40.0.0 py37_0
        - six 1.11.0 py37_1
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - hdf5 >=1.10.2,<1.10.3.0a0
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - h5py
about:
    description: 'H5py uses straightforward NumPy and Python metaphors, like dictionary
        and

        NumPy array syntax.

        '
    dev_url: https://github.com/h5py/h5py
    doc_url: http://docs.h5py.org
    home: http://www.h5py.org/
    license: BSD 3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pitrou
        - tacaswell
