# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/11d6870a-6760-4c82-7f27-024025d940c9/volume/rsync-recipes/jupyter_client-5.2.4-python_3.7-on-osx, last modified Mon Dec 17 11:56:46 2018
# ------------------------------------------------

package:
    name: jupyter_client
    version: 5.2.4
source:
    fn: jupyter_client-5.2.4.tar.gz
    sha256: b5f9cb06105c1d2d30719db5ffb3ea67da60919fb68deaefa583deccd8813551
    url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-5.2.4.tar.gz
build:
    entry_points:
        - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
        - jupyter-run = jupyter_client.runapp:main
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - jupyter_core
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.1
        - pyzmq >=13
        - tornado
        - traitlets
test:
    commands:
        - jupyter kernelspec list
        - jupyter run -h
    imports:
        - jupyter_client
about:
    description: 'jupyter client contains the reference implementation of the Jupyter

        protocol.It also provides Python API for starting, managing and

        communicating with Jupyter kernels.

        '
    dev_url: https://github.com/jupyter/jupyter_client
    doc_source_url: https://github.com/jupyter/jupyter_client/blob/master/docs/index.rst
    doc_url: http://jupyter-client.readthedocs.org/
    home: http://jupyter.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: Jupyter protocol implementation and client libraries
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carreau
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
