# This file created by conda-build 3.17.3
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/63493ae9-cc52-46a3-78b6-627a27eb8365/volume/rsync-recipes/libarchive-3.3.3-on-osx, last modified Wed Dec 12 12:03:20 2018
# ------------------------------------------------

package:
    name: libarchive
    version: 3.3.3
source:
    fn: libarchive-3.3.3.tar.gz
    patches:
        - 0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
        - 0002-xar-fix-bad-seek-in-move_reading_point.patch
        - 0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
        - 0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
        - 0006-VC-openssl-define-inline-as-__inline.patch
        - 0007-CMake-VC9-compatibility-ignore-some-warnings.patch
        - 0008-VC9-compatibility-remove-C99.patch
        - 0009-CMake-Force-Multi-threaded-DLL-runtime.patch
        - 0010-Use-CreateSymbolicLinkW-on-Windows-for-symlinks-WIP.patch
    sha256: 720da414e7aebb255fcdaee106894e4d30e2472ac1390c2c15b70c84c7479658
    url: https://github.com/libarchive/libarchive/archive/v3.3.3.tar.gz
build:
    number: '5'
    string: h786848e_5
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.16.1 pl526_0
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libiconv 1.15 hdd342a3_7
        - libtool 2.4.6 h1de35cc_5
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - perl 5.26.2 h4e221da_0
        - pkg-config 0.29.2 h3efe00b_8
    host:
        - bzip2 1.0.6 h1de35cc_5
        - icu 58.2 h4b95b61_1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libiconv 1.15 hdd342a3_7
        - libxml2 2.9.8 hab757c2_1
        - lz4-c 1.8.1.2 h1de35cc_0
        - lzo 2.10 h362108e_2
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
        - zstd 1.3.7 h5bba6e5_0
    run:
        - bzip2 >=1.0.6,<2.0a0
        - libiconv >=1.15,<2.0a0
        - libxml2 >=2.9.8,<2.10.0a0
        - lz4-c >=1.8.1.2,<1.9.0a0
        - lzo >=2.10,<3.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.3.7,<1.3.8.0a0
test:
    commands:
        - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
        - test -f "${PREFIX}/include/archive.h"
        - test -f "${PREFIX}/include/archive_entry.h"
        - test -f "${PREFIX}/lib/libarchive.a"
        - test -f "${PREFIX}/lib/libarchive.dylib"
        - bsdcat --version
        - bsdcpio --version
        - bsdtar --version
        - bsdtar -tf test/hello_world.xar
    files:
        - test/hello_world.xar
about:
    home: http://www.libarchive.org/
    license: BSD 2-Clause
    summary: Multi-format archive and compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
