# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/bottleneck-feedstock/recipe, last modified Tue Apr 17 13:32:35 2018
# ------------------------------------------------

package:
    name: bottleneck
    version: 1.2.1
source:
    fn: Bottleneck-1.2.1.tar.gz
    sha256: 6efcde5f830aed64feafca0359b51db0e184c72af8ba6675b4a99f263922eb36
    url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-1.2.1.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37h1d22016_1
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - intel-openmp 2018.0.3 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2018.0.3 1
        - ncurses 6.1 h0a44026_0
        - numpy 1.11.3 py37heee0a97_5
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
test:
    commands:
        - python -c "import bottleneck; bottleneck.test()"
    imports:
        - bottleneck
        - bottleneck.move
        - bottleneck.nonreduce
        - bottleneck.nonreduce_axis
        - bottleneck.reduce
        - bottleneck.slow
        - bottleneck.tests
    requires:
        - nose
about:
    description: 'Bottleneck is a collection of fast NumPy array functions written
        in

        Cython.

        '
    dev_url: https://github.com/kwgoodman/bottleneck
    doc_url: http://berkeleyanalytics.com/bottleneck
    home: http://berkeleyanalytics.com/bottleneck
    license: BSD 2-Clause
    license_family: BSD
    license_file: bottleneck/LICENSE
    summary: Fast NumPy array functions written in Cython.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - wesm
