# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/unicodecsv-feedstock/recipe, last modified Mon Sep 11 14:11:43 2017
# ------------------------------------------------

package:
    name: unicodecsv
    version: 0.14.1
source:
    fn: unicodecsv-0.14.1.tar.gz
    sha256: 018c08037d48649a0412063ff4eda26eaa81eff1546dbffa51fa5293276ff7fc
    url: https://pypi.io/packages/source/u/unicodecsv/unicodecsv-0.14.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - unicodecsv
about:
    description: 'The unicodecsv is a drop-in replacement for Python 2.7''s csv module
        which

        supports unicode strings without a hassle. Supported versions are python

        2.6, 2.7, 3.3, 3.4, 3.5, and pypy 2.4.0.

        '
    dev_url: https://github.com/jdunck/python-unicodecsv
    home: https://github.com/jdunck/python-unicodecsv
    license: BSD
    license_family: BSD
    license_file: /Users/rdonnelly/conda/aggregate/unicodecsv-feedstock/recipe/LICENSE
    summary: Drop-in replacement for csv module which supports unicode strings
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
