# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/wrapt-feedstock/recipe, last modified Tue Apr 17 13:44:18 2018
# ------------------------------------------------

package:
    name: wrapt
    version: 1.10.11
source:
    fn: wrapt-1.10.11.tar.gz
    sha256: d4d560d479f2c21e1b5443bbd15fe7ec4b37fe7e53d335d3b9b0a7b1226fe3c6
    url: https://pypi.io/packages/source/w/wrapt/wrapt-1.10.11.tar.gz
build:
    number: '2'
    script: python setup.py install
    string: py37h1de35cc_2
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - wrapt
about:
    description: 'The aim of the wrapt module is to provide a transparent object proxy
        for

        Python, which can be used as the basis for the construction of function

        wrappers and decorator functions.

        '
    dev_url: https://github.com/GrahamDumpleton/wrapt
    doc_source_url: https://github.com/GrahamDumpleton/wrapt/blob/master/docs/index.rst
    doc_url: http://wrapt.readthedocs.org/en/latest/
    home: https://github.com/GrahamDumpleton/wrapt
    license: BSD 2-Clause
    license_file: LICENSE
    summary: Module for decorators, wrappers and monkey patching.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
