# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/xlwt-feedstock/recipe, last modified Tue Apr 17 13:44:36 2018
# ------------------------------------------------

package:
    name: xlwt
    version: 1.3.0
source:
    fn: xlwt-1.3.0.tar.gz
    sha256: c59912717a9b28f1a3c2a98fd60741014b06b043936dcecbc113eaaada156c88
    url: https://pypi.io/packages/source/x/xlwt/xlwt-1.3.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - xlwt
about:
    description: 'Xlwt is a library for developers to use to generate spreadsheet
        files

        compatible with Microsoft Excel versions 95 to 2003.

        '
    dev_url: https://github.com/python-excel/xlwt
    doc_source_url: https://github.com/python-excel/xlwt/blob/master/docs/index.rst
    doc_url: http://xlwt.readthedocs.org/en/latest/
    home: http://www.python-excel.org/
    license: BSD
    license_family: BSD
    license_file: docs/licenses.rst
    summary: Writing data and formatting information to Excel files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
