# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/4524116b-42ec-4ffe-4c8f-2d82dbfa7551/volume/rsync-recipes/flask-cors-3.0.7-python_3.7-on-osx, last modified Mon Nov 12 20:14:18 2018
# ------------------------------------------------

package:
    name: flask-cors
    version: 3.0.7
source:
    fn: Flask-Cors-3.0.7.tar.gz
    sha256: 7e90bf225fdf163d11b84b59fb17594d0580a16b97ab4e1146b1fb2737c1cfec
    url: https://pypi.org/packages/source/F/Flask-Cors/Flask-Cors-3.0.7.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.1.1 h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.5.0 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.2 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - flask >=0.9
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - flask_cors
        - flask_cors.core
        - flask_cors.decorator
        - flask_cors.extension
        - flask_cors.version
about:
    description: 'A Flask extension for handling Cross Origin Resource Sharing (CORS),

        making cross-origin AJAX possible. This package exposes a Flask extension

        which by default enables CORS support on all routes, for all origins and

        methods.

        '
    dev_url: https://github.com/corydolphin/flask-cors
    doc_source_url: https://github.com/corydolphin/flask-cors/blob/master/docs/index.rst
    doc_url: http://flask-cors.corydolphin.com/en/latest/
    home: https://github.com/corydolphin/flask-cors
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A Flask extension adding a decorator for CORS support
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
