# This file created by conda-build 3.0.15+5.g16cf4af
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/pandoc-feedstock/recipe, last modified Mon Sep 11 14:09:02 2017
# ------------------------------------------------

package:
    name: pandoc
    version: 1.19.2.1
source:
    fn: pandoc-1.19.2.1.pkg
    sha256: 677ff56424de19d0f7f368aa9d9ece1b3fe03d7bd3e6bd0ad8f347debfcfafe5
    url: https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-osx.pkg
build:
    number: '1'
    string: ha5e8f32_1
test:
    commands:
        - pandoc --help
        - pandoc --version
about:
    description: 'Pandoc is a Haskell library for converting from one markup format
        to

        another, and a command-line tool that uses this library.

        '
    dev_url: https://github.com/jgm/pandoc
    doc_source_url: https://github.com/jgm/pandoc/tree/master/doc
    doc_url: http://pandoc.org/MANUAL.html
    home: http://johnmacfarlane.net/pandoc/
    license: GPL-2.0
    summary: Universal markup converter (repackaged binaries).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - janschulz
        - mingwandroid
        - ocefpaf
