# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/8986074a-104e-4c20-51c5-d2b4c5bac866/volume/rsync-recipes/dask-1.0.0-python_3.7-on-osx, last modified Thu Nov 29 08:56:56 2018
# ------------------------------------------------

package:
    name: dask
    version: 1.0.0
build:
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - bokeh >=0.13.0
        - cloudpickle >=0.2.1
        - cytoolz >=0.7.3
        - dask-core 1.0.0.*
        - distributed >=1.25.0
        - numpy >=1.11.0
        - pandas >=0.19.0
        - partd >=0.3.8
        - python >=3.7,<3.8.0a0
        - toolz >=0.7.3
test:
    imports:
        - dask
        - dask.array
        - dask.bag
        - dask.bytes
        - dask.dataframe
        - dask.dataframe.tseries
        - dask.delayed
        - dask.diagnostics
        - dask.distributed
        - distributed
about:
    description: 'Dask is a flexible parallel computing library for analytic computing.

        '
    dev_url: https://github.com/dask/dask
    doc_source_url: https://github.com/dask/dask/blob/master/docs/source/index.rst
    doc_url: https://dask.pydata.org/
    home: http://github.com/dask/dask/
    license: BSD 3-Clause
    summary: Parallel Python with task scheduling
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - alimanfoo
        - jakirkham
        - jcrist
        - koverholt
        - martindurant
        - mingwandroid
        - mrocklin
        - pitrou
        - shoyer
        - tomaugspurger
