# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/4c3fb241-6232-44a7-4e6b-b34bd03be1d8/volume/rsync-recipes/ipywidgets-7.4.2-python_3.7-on-osx, last modified Fri Sep 28 12:12:25 2018
# ------------------------------------------------

package:
    name: ipywidgets
    version: 7.4.2
source:
    sha256: a3e224f430163f767047ab9a042fc55adbcab0c24bbe6cf9f306c4f89fdf0ba3
    url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-7.4.2.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - ipykernel >=4.5.1
        - ipython >=4.0.0
        - nbformat >=4.2.0
        - python >=3.7,<3.8.0a0
        - traitlets >=4.3.1,<5.0.0
        - widgetsnbextension >=3.4.0,<3.5.0
test:
    imports:
        - ipywidgets
about:
    description: 'ipywidgets are interactive HTML widgets for Jupyter notebooks and
        the IPython kernel.

        '
    doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst
    doc_url: https://ipywidgets.readthedocs.io/en/latest/
    home: https://github.com/ipython/ipywidgets
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Jupyter Interactive Widgets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - jasongrout
        - maartenbreddels
        - minrk
        - pbugnion
        - pelson
        - willingc
