# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/fastcache-feedstock/recipe, last modified Tue Apr 17 13:34:12 2018
# ------------------------------------------------

package:
    name: fastcache
    version: 1.0.2
source:
    fn: fastcache-1.0.2.tar.gz
    sha256: 867005774917f999854ffd303fbe3793c30c2dc9279b78ec315dd4e57e4284e6
    url: https://pypi.io/packages/source/f/fastcache/fastcache-1.0.2.tar.gz
build:
    number: '2'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37h1de35cc_2
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    commands:
        - python -c "import fastcache; fastcache.test()"
    imports:
        - fastcache
        - fastcache._lrucache
    requires:
        - pytest
about:
    description: 'fastcache provides speedup of 10-30x over standard library.

        It passes test suite from standard library for lru_cache.

        '
    dev_url: https://github.com/pbrady/fastcache
    doc_source_url: https://github.com/pbrady/fastcache/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/fastcache/1.0.2
    home: https://github.com/pbrady/fastcache
    license: MIT
    license_family: MIT
    license_file: /Users/rdonnelly/conda/aggregate/fastcache-feedstock/recipe/LICENSE
    summary: C implementation of Python 3 lru_cache
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - synapticarbors
