# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# /opt/concourse/volumes/live/f48c229b-0fae-42c1-4709-1483b39b13c3/volume/rsync-recipes/gmp-6.1.2-on-osx, last modified Mon Nov 13 15:43:18 2017
# ------------------------------------------------

package:
    name: gmp
    version: 6.1.2
source:
    fn: gmp-6.1.2.tar.bz2
    sha256: 5275bb04f4863a13516b2f39392ac5e272f5e1bb8057b18aec1c9b79d73d8fb2
    url: https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2
build:
    number: '1'
    run_exports:
        - gmp >=6.1.2
    string: hb37e062_1
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h6c06975_3
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 hbbb0622_3
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - m4 1.4.18 hc7d0c60_0
    run:
        - libcxx  >=4.0.1
test:
    commands:
        - test -f ${PREFIX}/lib/libgmp.a
        - test -f ${PREFIX}/lib/libgmp.dylib
        - test -f ${PREFIX}/lib/libgmpxx.a
        - test -f ${PREFIX}/lib/libgmpxx.dylib
    files:
        - test.c
    requires:
        - clang_osx-64
about:
    home: http://gmplib.org/
    license: GPL 2 and LGPL 3
    license_file: COPYING.LESSERv3
    summary: The GNU multiprecision library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - isuruf
        - jakirkham
