# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/b22c1fc0-e9ce-49f4-6136-9b67c7334e53/volume/rsync-recipes/glob2-0.6-python_3.7-on-osx, last modified Tue Oct  2 17:20:04 2018
# ------------------------------------------------

package:
    name: glob2
    version: '0.6'
source:
    fn: glob2-0.6.tar.gz
    patches:
        - be6981ec1a3ec089a934dbce3717d9ee6a01584e.patch
    sha256: 4f554074f242f01b48a9537409cdbc5e31355a06b51950c95f93fc061c324149
    url: https://github.com/miracle2k/python-glob2/archive/0.6.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_1
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - glob2
about:
    description: 'The glob module finds all the pathnames matching a specified pattern
        according to the rules

        used by the Unix shell, although results are returned in arbitrary order.
        No tilde expansion

        is done, but *, ?, and character ranges expressed with [] will be correctly
        matched.

        '
    dev_url: https://github.com/miracle2k/python-glob2
    doc_url: https://docs.python.org/3/library/glob.html
    home: https://github.com/miracle2k/python-glob2
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Version of the glob module that supports recursion via **, and can capture
        patterns.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dfroger
