# This file created by conda-build 3.10.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/5edd5225-fd19-4186-5574-7bcb276198b9/volume/rsync-recipes/freetype-2.9.1-on-osx, last modified Thu May 24 07:09:03 2018
# ------------------------------------------------

package:
    name: freetype
    version: 2.9.1
source:
    fn: freetype-2.9.1.tar.bz2
    patches:
        - 0001-Unbreak-CMake-Windows-installation.patch
    sha256: db8d87ea720ea9d5edc5388fc7a0497bb11ba9fe972245e0f7f4c7e8b1e1e84d
    url: http://download.savannah.gnu.org/releases/freetype/freetype-2.9.1.tar.bz2
build:
    number: '0'
    run_exports:
        - freetype >=2.9.1,<3.0a0
    string: hb4e5f40_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - make 4.2.1 h3efe00b_1
    host:
        - libpng 1.6.34 he12f830_0
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libpng >=1.6.34,<1.7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - ${PREFIX}/bin/freetype-config --version
about:
    description: 'FreeType is designed to be small, efficient, highly customizable

        and portable while capable of producing high-quality output (glyph images)

        of most vector and bitmap font formats.

        '
    dev_url: http://git.savannah.gnu.org/cgit/freetype/
    doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
    doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
    home: https://www.freetype.org/
    license: GPL-2.0 and FreeType
    license_url: http://freetype.sourceforge.net/FTL.TXT
    summary: A Free, High-Quality, and Portable Font Engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - msarahan
        - ocefpaf
