# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/0820d69b-4d1c-49ae-6df3-82f2e453bd2d/volume/rsync-recipes/qtpy-1.5.2-python_3.7-on-osx, last modified Mon Oct 22 13:14:10 2018
# ------------------------------------------------

package:
    name: qtpy
    version: 1.5.2
source:
    fn: qtpy-1.5.2.tar.gz
    sha256: 4c690f90586c82c1210bb6fdf5e9ee4d1228809421dc6a349c5afacc27caabcd
    url: https://pypi.io/packages/source/q/qtpy/QtPy-1.5.2.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.4.3 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    requires:
        - pyqt
    script:
        - QT_API=pyqt5 qtpy
        - QT_API=pyqt5 qtpy.QtGui
about:
    description: 'QtPy is a small abstraction layer that lets you write applications
        using a

        single api call to either PyQt or PySide.

        '
    dev_url: https://github.com/spyder-ide/qtpy
    doc_source_url: https://github.com/spyder-ide/qtpy/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/QtPy
    home: https://github.com/spyder-ide/qtpy
    license: MIT
    license_file: LICENSE.txt
    summary: Abtraction layer for PyQt5/PyQt4/PySide
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Nodd
        - astrofrog-conda-forge
        - ccordoba12
        - goanpeca
