# This file created by conda-build 3.17.4
# ------------------------------------------------

package:
    name: mkl_fft
    version: 1.0.6
source:
    -   patches:
            - 0001-fix-windows-case-sensitivity.patch
            - 0002-simplify-arch-flags.patch
            - 0003-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
            - 0004-disable-memmap-filename-test-due-to-CI-link-confusio.patch
            - 0005-disable-broken-tests.patch
            - 0006-use-mklfft-when-available.patch
            - 0007-define-mkl_version-in-__init__.py.patch
            - 0008-intel-umath-optimizations.patch
            - 0009-intel-mkl_mem-all.patch
            - 0010-intel-init_mkl.patch
            - 0011-intel-mkl_random.patch
            - 0012-Remove-ICC-specific-flags.patch
            - 0013-Remove-np.invsqrt.patch
            - 0014-Rewrite-inlining.patch
        sha256: 3d734559db35aa3697dadcea492a423118c5c55d176da2f3be9c98d4803fc2a7
        url: https://pypi.io/packages/source/n/numpy/numpy-1.15.4.zip
    -   folder: mkl_random
        sha256: 2270ef2834f6552850533aad01500d27c8e056f2cfbdbdb751593000aea1159e
        url: https://github.com/IntelPython/mkl_random/archive/v1.0.2.tar.gz
    -   folder: mkl_fft
        sha256: 3c7ed29e203c5b664ecafb11d767d62f9cae4aa56f9a95737e121192a66673bf
        url: https://github.com/IntelPython/mkl_fft/archive/v1.0.6.tar.gz
build:
    number: 0
    script: pushd mkl_fft && python setup.py build install --single-version-externally-managed
        --record=record.txt
    string: py37h27c97d8_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - cython 0.29 py37h0a44026_0
        - intel-openmp 2019.1 144
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - mkl 2019.1 144
        - mkl-devel 2019.1 144
        - mkl-include 2019.1 144
        - ncurses 6.1 h0a44026_1
        - numpy-base 1.11.*
        - openssl 1.1.1a h1de35cc_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - libcxx >=4.0.1
        - mkl >=2019.1,<2020.0a0
        - numpy-base >=1.0.6,<2.0a0
        - python >=3.7,<3.8.0a0
test:
    commands:
        - nosetests -v mkl_fft
    imports:
        - mkl_fft
        - mkl_fft._numpy_fft
        - mkl_fft._scipy_fft
    requires:
        - nose
about:
    description: NumPy-based implementation of Fast Fourier Transform using Intel
        (R) Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex
        FFT on arrays of single and double precision with arbitrary memory layout,
        so long as array strides are multiples of its itemsize.
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R)
        Math Kernel Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
