# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/2cab5fba-3e75-4ccb-5f84-23b9c823e85f/volume/rsync-recipes/beautifulsoup4-4.6.3-python_3.7-on-osx, last modified Mon Aug 13 10:19:46 2018
# ------------------------------------------------

package:
    name: beautifulsoup4
    version: 4.6.3
source:
    sha256: 90f8e61121d6ae58362ce3bed8cd997efb00c914eae0ff3d363c32f9a9822d10
    url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-4.6.3.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h1de35cc_1
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 40.0.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - bs4
about:
    description: 'Beautiful Soup is a library for pulling data out of HTML and XML
        files.

        It provides ways of navigating, searching, and modifying parse trees.

        '
    dev_url: https://code.launchpad.net/beautifulsoup
    doc_source_url: https://github.com/newvem/beautifulsoup4/blob/master/doc/source/index.rst
    doc_url: http://beautiful-soup-4.readthedocs.io/en/latest/
    home: http://www.crummy.com/software/BeautifulSoup/
    license: MIT
    license_family: MIT
    license_file: COPYING.txt
    summary: Python library designed for screen-scraping
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
        - nehaljwani
