# This file created by conda-build 3.14.4
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/3708e416-b515-407b-4727-e00836525bb7/volume/rsync-recipes/defusedxml-0.5.0-python_3.7-on-osx, last modified Wed Sep 12 14:56:45 2018
# ------------------------------------------------

package:
    name: defusedxml
    version: 0.5.0
source:
    fn: defusedxml-0.5.0.tar.gz
    sha256: 24d7f2f94f7f3cb6061acb215685e5125fbcdc40a857eff9de22518820b0a4f4
    url: https://pypi.io/packages/source/d/defusedxml/defusedxml-0.5.0.tar.gz
build:
    number: '1'
    script: /opt/concourse/worker/volumes/live/3708e416-b515-407b-4727-e00836525bb7/volume/defusedxml_1536782399052/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_1
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - defusedxml
about:
    dev_url: https://bitbucket.org/tiran/defusedxml
    doc_url: https://bitbucket.org/tiran/defusedxml
    home: https://bitbucket.org/tiran/defusedxml
    license: PSF 2.0
    license_family: PSF
    license_file: LICENSE
    summary: XML bomb protection for Python stdlib modules
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
