# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a8192935-07b4-4e67-491b-df396b1e4545/volume/rsync-recipes/ipykernel-5.1.0-python_3.7-on-osx, last modified Thu Oct 18 11:14:17 2018
# ------------------------------------------------

package:
    name: ipykernel
    version: 5.1.0
source:
    sha256: 0fc0bf97920d454102168ec2008620066878848fcfca06c22b669696212e292f
    url: https://pypi.io/packages/source/i/ipykernel/ipykernel-5.1.0.tar.gz
build:
    number: '0'
    script:
        - /opt/concourse/worker/volumes/live/a8192935-07b4-4e67-491b-df396b1e4545/volume/ipykernel_1539879519768/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
            -m pip install . --no-deps --ignore-installed -vvv
        - python -m ipykernel install --prefix /opt/concourse/worker/volumes/live/a8192935-07b4-4e67-491b-df396b1e4545/volume/ipykernel_1539879519768/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
    string: py37h39e3cac_0
requirements:
    host:
        - appnope 0.1.0 py37_0
        - backcall 0.1.0 py37_0
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - decorator 4.3.0 py37_0
        - ipython 7.0.1 py37h39e3cac_0
        - ipython_genutils 0.2.0 py37_0
        - jedi 0.13.1 py37_0
        - jupyter_client 5.2.3 py37_0
        - jupyter_core 4.4.0 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libsodium 1.0.16 h3efe00b_0
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - parso 0.3.1 py37_0
        - pexpect 4.6.0 py37_0
        - pickleshare 0.7.5 py37_0
        - pip 10.0.1 py37_0
        - prompt_toolkit 2.0.6 py37_0
        - ptyprocess 0.6.0 py37_0
        - pygments 2.2.0 py37_0
        - python 3.7.0 hc167b69_0
        - python-dateutil 2.7.3 py37_0
        - pyzmq 17.1.2 py37h1de35cc_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.4.3 py37_0
        - simplegeneric 0.8.1 py37_2
        - six 1.11.0 py37_1
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - tornado 5.1.1 py37h1de35cc_0
        - traitlets 4.3.2 py37_0
        - wcwidth 0.1.7 py37_0
        - wheel 0.32.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zeromq 4.2.5 h0a44026_1
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - ipython >=5.0
        - jupyter_client
        - python >=3.7,<3.8.0a0
        - tornado >=4.0
        - traitlets >=4.1
test:
    commands:
        - jupyter kernelspec list
        - pytest --pyargs ipykernel
    imports:
        - ipykernel
    requires:
        - matplotlib
        - nose
        - numpy
        - pytest
about:
    description: 'A powerful interactive Python shell and a Jupyter kernel to work
        with

        Python code in Jupyter notebooks and other interactive frontends.

        '
    dev_url: https://github.com/ipython/ipykernel
    doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
    doc_url: https://ipython.readthedocs.io
    home: https://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: IPython Kernel for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
