# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/kiwisolver-feedstock/recipe, last modified Tue Apr 17 13:36:33 2018
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.0.1
source:
    fn: kiwisolver-1.0.1.tar.gz
    sha256: 8e7fc64fea6d3af96aed63391d35bbbd292a429c8e463277dac839b735503a28
    url: https://github.com/nucleic/kiwi/archive/1.0.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37h0a44026_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - libcxx >=4.0.1
        - python >=3.7,<3.8.0a0
test:
    imports:
        - kiwisolver
about:
    description: 'Kiwi is an implementation of the algorithm based on the seminal

        Cassowary paper.It is not a refactoring of the original C++ solver.

        Kiwi has been designed from the ground up to be lightweight and fast.

        '
    dev_url: https://github.com/nucleic/kiwi
    doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/kiwisolver
    home: https://github.com/nucleic/kiwi
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING.txt
    summary: A fast implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - sccolbert
        - tacaswell
