# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/blaze-feedstock/recipe, last modified Mon Sep 11 14:05:02 2017
# ------------------------------------------------

package:
    name: blaze
    version: 0.11.3
source:
    fn: blaze-0.11.3.tar.gz
    sha256: 9c3725759d20ecf164b38c125a0417c2d294f0fa657367c92748bcd312c3af1c
    url: https://github.com/blaze/blaze/archive/0.11.3.tar.gz
build:
    entry_points:
        - blaze-server = blaze.server.spider:_main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - blas 1.0 mkl
        - bokeh 0.13.0 py37_0
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - click 6.7 py37_0
        - cloudpickle 0.5.3 py37_0
        - cytoolz 0.9.0.1 py37h1de35cc_1
        - dask 0.18.1 py37_0
        - dask-core 0.18.1 py37_0
        - datashape 0.5.4 py37_1
        - decorator 4.3.0 py37_0
        - distributed 1.22.0 py37_0
        - flask 1.0.2 py37_1
        - flask-cors 3.0.6 py37_0
        - heapdict 1.0.0 py37_2
        - intel-openmp 2018.0.3 0
        - itsdangerous 0.24 py37_1
        - jinja2 2.10 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - locket 0.2.0 py37_1
        - markupsafe 1.0 py37h1de35cc_1
        - mkl 2018.0.3 1
        - mkl_fft 1.0.2 py37h6b9c3cc_0
        - mkl_random 1.0.1 py37h5d10147_1
        - msgpack-python 0.5.6 py37h04f5b5a_0
        - multipledispatch 0.5.0 py37_0
        - ncurses 6.1 h0a44026_0
        - networkx 2.1 py37_0
        - numpy 1.14.5 py37h648b28d_0
        - numpy-base 1.14.5 py37ha9ae307_0
        - odo 0.5.1 py37_0
        - openssl 1.0.2o h26aff7b_0
        - packaging 17.1 py37_0
        - pandas 0.23.1 py37h6440ff4_0
        - partd 0.3.8 py37_0
        - psutil 5.4.6 py37h1de35cc_0
        - pyparsing 2.2.0 py37_1
        - python 3.7.0 hc167b69_0
        - python-dateutil 2.7.3 py37_0
        - pytz 2018.5 py37_0
        - pyyaml 3.12 py37h1de35cc_1
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - six 1.11.0 py37_1
        - sortedcontainers 2.0.4 py37_0
        - sqlalchemy 1.2.8 py37h1de35cc_0
        - sqlite 3.24.0 ha441bb4_0
        - tblib 1.3.2 py37_0
        - tk 8.6.7 h35a86e2_3
        - toolz 0.9.0 py37_0
        - tornado 5.0.2 py37h1de35cc_0
        - werkzeug 0.14.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - yaml 0.1.7 hc338f04_2
        - zict 0.1.3 py37_0
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - cytoolz
        - dask
        - datashape >=0.5.3
        - flask >=0.10.1
        - flask-cors
        - h5py
        - numba
        - odo >=0.5.0
        - psutil
        - pytables >=3.0.0
        - python >=3.7,<3.8.0a0
        - pyyaml
        - requests
        - sqlalchemy >=0.8.0
test:
    imports:
        - blaze
        - blaze.compute
        - blaze.expr
        - blaze.tests
about:
    description: 'Blaze Ecosystem provides Python users high-level access to efficient

        computation on inconveniently large data.  Blaze can refer to both a particular

        library as well as an ecosystem of related projects that have spun off of
        Blaze

        development.

        '
    dev_url: https://github.com/blaze/blaze
    doc_source_url: https://github.com/blaze/blaze/blob/master/docs/source/index.rst
    doc_url: http://blaze.readthedocs.io/en/latest/index.html
    home: http://blaze.pydata.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: NumPy and Pandas interface to big data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
