# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/1287d6ba-51a9-452b-52df-af1b72a4124a/volume/rsync-recipes/sphinx-1.8.2-python_3.7-on-osx, last modified Mon Nov 12 20:15:27 2018
# ------------------------------------------------

package:
    name: sphinx
    version: 1.8.2
source:
    sha256: 120732cbddb1b2364471c3d9f8bfd4b0c5b550862f99a65736c77f970b142aea
    url: https://pypi.io/packages/source/S/Sphinx/Sphinx-1.8.2.tar.gz
build:
    entry_points:
        - sphinx-apidoc = sphinx.ext.apidoc:main
        - sphinx-autogen = sphinx.ext.autosummary.generate:main
        - sphinx-build = sphinx.cmd.build:main
        - sphinx-quickstart = sphinx.cmd.quickstart:main
    number: '0'
    script:
        - /opt/concourse/worker/volumes/live/1287d6ba-51a9-452b-52df-af1b72a4124a/volume/sphinx_1542090042754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
            -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.1.1 h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.5.0 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.2 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - alabaster >=0.7,<0.8
        - babel >=1.3,!=2.0
        - docutils >=0.11
        - imagesize
        - jinja2 >=2.3
        - packaging
        - pygments >=2.0
        - python >=3.7,<3.8.0a0
        - requests >=2.0.0
        - setuptools
        - six >=1.5
        - snowballstemmer >=1.1
        - sphinxcontrib-websupport
test:
    commands:
        - sphinx-build -h
        - sphinx-quickstart --version
        - sphinx-quickstart -h
        - sphinx-apidoc -h
        - sphinx-autogen -h
    imports:
        - sphinx
        - sphinx.pycode
about:
    description: 'Sphinx is a tool that makes it easy to create intelligent and beautiful
        documentation,

        written by Georg Brandl and licensed under the BSD license.

        It was originally created for the new Python documentation, and it has excellent

        facilities for the documentation of Python projects, but C/C++ is already
        supported

        as well, and it is planned to add special support for other languages as well.

        '
    dev_url: https://github.com/sphinx-doc/sphinx
    doc_source_url: https://github.com/sphinx-doc/sphinx/blob/master/doc/contents.rst
    doc_url: http://www.sphinx-doc.org/en/stable/contents.html
    home: http://www.sphinx-doc.org
    license: BSD 2-clause
    license_file: LICENSE
    summary: Sphinx is a tool that makes it easy to create intelligent and beautiful
        documentation
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - chohner
        - jakirkham
        - ocefpaf
