# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/zict-feedstock/recipe, last modified Tue Apr 17 13:44:48 2018
# ------------------------------------------------

package:
    name: zict
    version: 0.1.3
source:
    fn: zict-0.1.3.tar.gz
    sha256: 63377f063086fc92e5c16e4d02162c571f6470b9e796cf3411ef9e815c96b799
    url: https://pypi.io/packages/source/z/zict/zict-0.1.3.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - heapdict
        - python >=3.7,<3.8.0a0
test:
    imports:
        - zict
about:
    description: 'Mutable Mapping interfaces.

        '
    dev_url: https://github.com/dask/zict
    doc_source_url: https://github.com/dask/zict/tree/master/doc
    doc_url: http://zict.readthedocs.io/en/latest/
    home: http://github.com/mrocklin/zict
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Composable Dictionary Classes
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mrocklin
        - pitrou
