# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/anaconda-project-feedstock/recipe, last modified Tue Apr 17 13:31:43 2018
# ------------------------------------------------

package:
    name: anaconda-project
    version: 0.8.2
source:
    fn: anaconda-project-0.8.2.tar.gz
    patches:
        - 001-setup.py.patch
    sha256: 2c79d1b38b4c0cbccba6965e2ab2483cdf8dcbc7c69b73ef42d639cfe7b62e89
    url: https://pypi.io/packages/source/a/anaconda-project/anaconda-project-0.8.2.tar.gz
build:
    entry_points:
        - anaconda-project = anaconda_project.cli:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - anaconda-client
        - python >=3.7,<3.8.0a0
        - requests
        - ruamel_yaml
        - tornado >=4.2
test:
    commands:
        - echo "First of test commands"
        - anaconda-project --help
        - anaconda-project --version
        - echo "Last of test commands"
    imports:
        - anaconda_project
about:
    description: 'By adding an anaconda-project.yml to a project directory, a single

        anaconda-project runcommand will be able to set up all dependencies

        and then launch the project.

        '
    dev_url: https://github.com/Anaconda-Platform/anaconda-project
    doc_url: http://anaconda-project.readthedocs.io
    home: https://github.com/Anaconda-Platform/anaconda-project
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Tool for encapsulating, running, and reproducing data science projects
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - fpliger
        - goanpeca
        - mingwandroid
