# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/statsmodels-feedstock/recipe, last modified Wed May 16 02:04:56 2018
# ------------------------------------------------

package:
    name: statsmodels
    version: 0.9.0
source:
    fn: statsmodels-0.9.0.tar.gz
    sha256: 6461f93a842c649922c2c9a9bc9d9c4834110b89de8c4af196a791ab8f42ba3b
    url: https://pypi.io/packages/source/s/statsmodels/statsmodels-0.9.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37h1d22016_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - cython 0.28.3 py37h1de35cc_0
        - intel-openmp 2018.0.3 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2018.0.3 1
        - ncurses 6.1 h0a44026_0
        - numpy 1.11.3 py37heee0a97_5
        - openssl 1.0.2o h26aff7b_0
        - pandas 0.23.1 py37h6440ff4_0
        - patsy 0.5.0 py37_0
        - python 3.7.0 hc167b69_0
        - python-dateutil 2.7.3 py37_0
        - pytz 2018.5 py37_0
        - readline 7.0 hc1231fa_4
        - scipy 1.1.0 py37hf1f7d93_0
        - setuptools 39.2.0 py37_0
        - six 1.11.0 py37_1
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - numpy >=1.11.3,<2.0a0
        - pandas >=0.14
        - patsy >=0.4.0
        - python >=3.7,<3.8.0a0
        - scipy >=0.14
test:
    imports:
        - statsmodels
about:
    description: 'Statsmodels is a Python module that allows users to explore data,
        estimate

        statistical models, and perform statistical tests. An extensive list of

        descriptive statistics, statistical tests, plotting functions, and result

        statistics are available for different types of data and each estimator.

        Researchers across fields may find that statsmodels fully meets their

        needs for statistical computing and data analysis in Python.

        '
    dev_url: https://github.com/statsmodels/statsmodels/
    doc_source_url: https://github.com/statsmodels/statsmodels/blob/master/docs/source/index.rst
    doc_url: http://statsmodels.sourceforge.net/documentation.html
    home: https://www.statsmodels.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Statistical computations and models for use with SciPy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - croth1
        - tomaugspurger
