# This file created by conda-build 3.17.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/02d401b3-1e0a-48bf-6037-33c14ed40856/volume/rsync-recipes/matplotlib-3.0.2-python_3.7-on-osx, last modified Tue Dec 11 11:22:38 2018
# ------------------------------------------------

package:
    name: matplotlib
    version: 3.0.2
source:
    sha256: 4682a2a4e66eed054d78a1eae5936d2174e8c145486db59f12a585aef991fad5
    url: https://github.com/matplotlib/matplotlib/archive/v3.0.2.tar.gz
build:
    ignore_run_exports:
        - pyqt
    number: '0'
    string: py37h54f8f79_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - cycler 0.10.0 py37_0
        - freetype 2.9.1 hb4e5f40_0
        - intel-openmp 2019.1 144
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - libiconv 1.15 hdd342a3_7
        - libpng 1.6.35 ha441bb4_0
        - mkl 2018.0.3 1
        - ncurses 6.1 h0a44026_1
        - nose 1.3.7 py37_2
        - numpy 1.11.3 py37h6a91979_10
        - numpy-base 1.11.3 py37h8a80b8c_10
        - openssl 1.1.1a h1de35cc_0
        - pkg-config 0.29.2 h3efe00b_8
        - pyparsing 2.3.0 py37_0
        - python 3.7.1 haf84260_3
        - python-dateutil 2.7.5 py37_0
        - pytz 2018.7 py37_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - six 1.11.0 py37_1
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - cycler >=0.10
        - freetype >=2.9.1,<3.0a0
        - kiwisolver
        - libcxx >=4.0.1
        - libpng >=1.6.35,<1.7.0a0
        - numpy
        - pyparsing
        - python >=3.7,<3.8.0a0
        - python-dateutil
        - pytz
        - setuptools
        - tornado
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - conda inspect objects -p $PREFIX $PKG_NAME
    imports:
        - matplotlib
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.backends._tkagg
        - matplotlib.ft2font
        - matplotlib.pyplot
        - matplotlib.ttconv
        - mpl_toolkits
        - pylab
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
