# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/12de9f1f-46df-43be-7546-838dade2db02/volume/rsync-recipes/qtawesome-0.5.3-python_3.7-on-osx, last modified Fri Nov 16 09:30:52 2018
# ------------------------------------------------

package:
    name: qtawesome
    version: 0.5.3
source:
    sha256: 8dfd8bcac56caa6d81639fc43db673b62aeca6129f4c8e9b1da17a32c0d309fd
    url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-0.5.3.tar.gz
build:
    noarch: false
    number: '0'
    script: /opt/concourse/worker/volumes/live/12de9f1f-46df-43be-7546-838dade2db02/volume/qtawesome_1542392041352/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.1.1 h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.5.0 py37_0
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.2 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
        - qtpy
        - six
test:
    imports:
        - qtawesome
    requires:
        - pyqt
about:
    home: https://github.com/spyder-ide/qtawesome
    license: MIT
    license_file: LICENSE
    summary: Iconic fonts in PyQt and PySide applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - ccordoba12
        - goanpeca
