# This file created by conda-build 3.16.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/578c7ff9-b5b0-4c2a-7eb3-dfed3ff64bca/volume/rsync-recipes/jupyterlab_server-0.2.0-python_3.7-on-osx, last modified Tue Oct  9 09:21:43 2018
# ------------------------------------------------

package:
    name: jupyterlab_server
    version: 0.2.0
source:
    fn: jupyterlab_server-0.2.0.tar.gz
    sha256: 72d916a73957a880cdb885def6d8664a6d1b2760ef5dca5ad665aa1e8d1bb783
    url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-0.2.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/578c7ff9-b5b0-4c2a-7eb3-dfed3ff64bca/volume/jupyterlab_server_1539095178439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps --ignore-installed -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.4.3 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.0 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - notebook
        - python >=3.7,<3.8.0a0
test:
    imports:
        - jupyterlab_server
about:
    home: http://github.com/jupyterlab/jupyterlab_server
    license: BSD 3-Clause
    license_file: LICENSE
    summary: A set of server components for JupyterLab and JupyterLab like applications.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - afshin
        - blink1073
        - jasongrout
