# This file created by conda-build 3.17.3
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/17951910-be27-42c4-61eb-36a821c14e8b/volume/rsync-recipes/scikit-image-0.14.1-python_3.7-on-osx, last modified Tue Dec 11 23:04:21 2018
# ------------------------------------------------

package:
    name: scikit-image
    version: 0.14.1
source:
    git_rev: v0.14.1
    git_url: https://github.com/scikit-image/scikit-image
    patches:
        - 0001-_marching_cubes_lewiner_cy-mark-char-as-signed.patch
        - 0002-Mark-some-tests-as-xfail-if-numpy-uses-mkl.patch
        - 3458.patch
build:
    entry_points:
        - skivi = skimage.scripts.skivi:main
    number: '0'
    script:
        - rm -rf skimage/viewer/tests
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py37h0a44026_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - cython 0.29 py37h0a44026_0
        - intel-openmp 2019.1 144
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2018.0.3 1
        - ncurses 6.1 h0a44026_1
        - numpy 1.11.3 py37h6a91979_10
        - numpy-base 1.11.3 py37h8a80b8c_10
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - scipy 1.1.0 py37hf5b7bf4_0
        - setuptools 40.6.2 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - cloudpickle >=0.2.1
        - cytoolz >=0.7.3
        - dask-core >=0.9.0
        - imageio >=2.1.0
        - libcxx >=4.0.1
        - matplotlib >=2.0.0
        - networkx >=1.8
        - numpy >=1.11.3,<2.0a0
        - pillow >=4.3.0
        - python >=3.7,<3.8.0a0
        - pywavelets >=0.4.0
        - scipy >=0.17
        - six >=1.7.3
        - toolz >=0.7.4
test:
    commands:
        - export MPLBACKEND=Agg
        - pytest --pyargs skimage
    imports:
        - skimage
    requires:
        - pytest
        - pytest-cov
about:
    home: http://scikit-image.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Image processing routines for SciPy.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Korijn
        - ivoflipse
        - jakirkham
        - jni
        - mingwandroid
        - msarahan
        - ocefpaf
        - soupault
