# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/cba2ce25-36a3-43ff-7300-a7e4c8893167/volume/rsync-recipes/pygments-2.3.1-python_3.7-on-osx, last modified Mon Dec 17 11:56:55 2018
# ------------------------------------------------

package:
    name: pygments
    version: 2.3.1
source:
    fn: Pygments-2.3.1.tar.gz
    sha256: 5ffada19f6203563680669ee7f53b64dabbeb100eb51b61996085e99c03b284a
    url: https://pypi.io/packages/source/P/Pygments/Pygments-2.3.1.tar.gz
build:
    entry_points:
        - pygmentize = pygments.cmdline:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - python 3.7.1 haf84260_7
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.26.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - pygmentize -h
    imports:
        - pygments
        - pygments.filters
        - pygments.formatters
        - pygments.lexers
        - pygments.plugin
        - pygments.styles
about:
    description: 'Pygments is suitable for use in code hosting, forums, wikis or other
        a

        pplications that need to prettify source code.

        '
    dev_url: https://bitbucket.org/birkenfeld/pygments-main
    doc_source_url: https://bitbucket.org/birkenfeld/pygments-main/src/defaults/doc/docs/
    doc_url: http://pygments.org/docs/
    home: http://pygments.org/
    license: BSD 2-clause
    license_file: LICENSE
    summary: Generic syntax highlighting package
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - pelson
        - scopatz
