# This file created by conda-build 3.10.4
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/de985aaa-ee1b-4790-4875-30dfb9dad0c7/volume/rsync-recipes/libxml2-2.9.8-on-osx, last modified Tue May 22 21:47:15 2018
# ------------------------------------------------

package:
    name: libxml2
    version: 2.9.8
source:
    patches:
        - 0001-C89-for-VS2008.patch
        - 0004-CVE-2017-8872.patch
    sha256: 0b74e51595654f958148759cfef0993114ddccccbb6f31aee018f3558e8e2732
    url: ftp://xmlsoft.org/libxml2/libxml2-2.9.8.tar.gz
build:
    number: 1
    run_exports:
        - libxml2 >=2.9.8,<2.10.0a0
    string: hab757c2_1
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.15.1 pl526h2ca55ef_0
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libiconv 1.15 hdd342a3_7
        - libtool 2.4.6 hdb3952c_3
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - perl 5.26.0 h5b8ca18_0
        - pkg-config 0.29.2 h3efe00b_8
    host:
        - icu 58.2 h4b95b61_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libiconv 1.15 hdd342a3_7
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - icu >=58.2,<59.0a0
        - libiconv >=1.15,<2.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - xmllint test.xml
        - conda inspect linkages -p $PREFIX libxml2
        - conda inspect objects -p $PREFIX libxml2
    files:
        - test.xml
about:
    description: 'Though libxml2 is written in C a variety of language

        bindings make it available in other environments.

        '
    dev_url: https://git.gnome.org/browse/libxml2/
    doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
    doc_url: http://xmlsoft.org/html/index.html
    home: http://xmlsoft.org/
    license: MIT
    license_family: MIT
    license_file: Copyright
    summary: The XML C parser and toolkit of Gnome
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - jakirkham
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
