# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/59e8f5bd-7d22-4f6d-7e56-b86f247921ab/volume/rsync-recipes/libiconv-1.15-on-osx, last modified Fri Nov 10 16:19:42 2017
# ------------------------------------------------

package:
    name: libiconv
    version: '1.15'
source:
    fn: libiconv-1.15.tar.gz
    sha256: ccf536620a45458d26ba83887a983b96827001e92a13847b45e4925cc8913178
    url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz
build:
    number: '7'
    run_exports:
        - libiconv >=1.15,<2.0a0
    string: hdd342a3_7
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h6c06975_3
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
test:
    commands:
        - iconv --help
        - conda inspect linkages -p $PREFIX libiconv
        - conda inspect objects -p $PREFIX libiconv
about:
    description: 'This library provides an iconv() implementation, for use on systems
        which don''t have one,

        or whose implementation cannot convert from/to Unicode.

        '
    dev_url: http://git.savannah.gnu.org/cgit/libiconv.git/tree/
    doc_url: https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.15/iconv.1.html
    home: https://www.gnu.org/software/libiconv/
    license: GPL and LGPL
    summary: Provides iconv for systems which don't have one (or that cannot convert
        from/to Unicode.)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jhamman
        - ocefpaf
