# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/bkcharts-feedstock/recipe, last modified Mon Sep 11 14:05:00 2017
# ------------------------------------------------

package:
    name: bkcharts
    version: '0.2'
source:
    fn: bkcharts-0.2.tar.gz
    sha256: a5eaa8e78853dcecaa46345812e4fabe9cd3b96330ebf0809f640a4a0556d72e
    url: https://pypi.io/packages/source/b/bkcharts/bkcharts-0.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - numpy >=1.7.1
        - pandas
        - python >=3.7,<3.8.0a0
        - six >=1.5.2
about:
    dev_url: http://github.com/bokeh/bkcharts
    home: http://github.com/bokeh/bkcharts
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: High level chart types built on top of Bokeh
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
