# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/fc349476-4d47-4aba-614c-b7c913ff227b/volume/rsync-recipes/conda-verify-3.1.1-python_3.7-on-osx, last modified Fri Sep 28 10:28:12 2018
# ------------------------------------------------

package:
    name: conda-verify
    version: 3.1.1
source:
    fn: conda-verify-3.1.1.tar.gz
    sha256: 2697f5525f0b33b5e6fb288db0f6e72a4b895492ee344e8795c6de7f64dbd2a0
    url: https://github.com/conda/conda-verify/archive/3.1.1.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/fc349476-4d47-4aba-614c-b7c913ff227b/volume/conda-verify_1538577430804/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - click
        - future
        - jinja2
        - python >=3.7,<3.8.0a0
        - pyyaml
        - six
test:
    commands:
        - conda-verify --version
        - conda-verify --help
    imports:
        - conda_verify
about:
    description: 'conda-verify is a tool for (passively) verifying conda recipes and
        conda

        packages.

        '
    home: https://github.com/conda/conda-verify
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: tool for validating conda recipes and conda packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mandeep
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
