# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/pyopenssl-feedstock/recipe, last modified Fri May 25 07:02:34 2018
# ------------------------------------------------

package:
    name: pyopenssl
    version: 18.0.0
source:
    sha256: 6488f1423b00f73b7ad5167885312bb0ce410d3312eb212393795b53c8caa580
    url: https://pypi.io/packages/source/p/pyOpenSSL/pyOpenSSL-18.0.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - cryptography >=2.2.1
        - python >=3.7,<3.8.0a0
        - six >=1.5.2
test:
    imports:
        - OpenSSL
        - OpenSSL.SSL
        - OpenSSL.crypto
        - OpenSSL.rand
about:
    description: 'pyOpenSSL is a high-level wrapper around a subset of the OpenSSL
        library.

        It includes:

        -SSL.Connection objects, wrapping the methods of Python''s portable sockets

        -Callbacks written in Python

        -Extensive error-handling mechanism, mirroring OpenSSL''s error codes

        and much more.

        '
    dev_url: https://github.com/pyca/pyopenssl
    doc_source_url: https://github.com/pyca/pyopenssl/blob/master/doc/index.rst
    doc_url: https://pyopenssl.readthedocs.org/en/stable/
    home: https://github.com/pyca/pyopenssl
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Python wrapper module around the OpenSSL library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - mingwandroid
        - nehaljwani
