# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/backports.shutil_get_terminal_size-feedstock/recipe, last modified Tue Apr 17 13:32:10 2018
# ------------------------------------------------

package:
    name: backports.shutil_get_terminal_size
    version: 1.0.0
source:
    fn: backports.shutil_get_terminal_size-1.0.0.tar.gz
    sha256: 713e7a8228ae80341c70586d1cc0a8caa5207346927e23d09dcbcaf18eadec80
    url: https://pypi.io/packages/source/b/backports.shutil_get_terminal_size/backports.shutil_get_terminal_size-1.0.0.tar.gz
build:
    number: '2'
    script: pip install --no-deps .
    string: py37_2
requirements:
    host:
        - backports 1.0 py37_1
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - backports
        - python >=3.7,<3.8.0a0
test:
    imports:
        - backports
        - backports.shutil_get_terminal_size
about:
    home: https://github.com/chrippa/backports.shutil_get_terminal_size
    license: MIT
    license_file: LICENSE
    summary: A backport of the get_terminal_size function from Python 3.3's shutil.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
