# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/bfceaa3e-575e-4396-5420-ffffcfe6017c/volume/rsync-recipes/packaging-18.0-python_3.7-on-osx, last modified Wed Oct  3 10:05:53 2018
# ------------------------------------------------

package:
    name: packaging
    version: '18.0'
source:
    sha256: 0886227f54515e592aaa2e5a553332c73962917f2831f1b0f9b9f4380a4b9807
    url: https://pypi.io/packages/source/p/packaging/packaging-18.0.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2p h1de35cc_0
        - pip 10.0.1 py37_0
        - pyparsing 2.2.1 py37_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 h1de35cc_5
        - setuptools 40.2.0 py37_0
        - six 1.11.0 py37_1
        - sqlite 3.25.2 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - pyparsing
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - packaging
about:
    dev_url: https://github.com/pypa/packaging
    doc_source_url: https://github.com/pypa/packaging/tree/master/docs
    doc_url: https://packaging.pypa.io/en/latest/
    home: https://github.com/pypa/packaging
    license: Apache 2.0 or BSD 2-Clause
    license_file: LICENSE
    summary: Core utilities for Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - nicoddemus
