# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/153d075d-7415-4eed-6f65-622e96e58f32/volume/rsync-recipes/dask-core-1.0.0-python_3.7-on-osx, last modified Thu Nov 29 08:56:32 2018
# ------------------------------------------------

package:
    name: dask-core
    version: 1.0.0
source:
    fn: dask-1.0.0.tar.gz
    sha256: a1fa4a3b2d7ce4dd0c68db4b68dadf2c283ff54d98bd72c556fc462000449ff7
    url: https://pypi.io/packages/source/d/dask/dask-1.0.0.tar.gz
build:
    noarch: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - pip 18.1 py37_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - dask
about:
    dev_url: https://github.com/dask/dask
    doc_url: https://dask.pydata.org/
    home: http://github.com/dask/dask/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Parallel Python with task scheduling
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - martindurant
        - mrocklin
        - pitrou
        - shoyer
        - sinhrks
        - tomaugspurger
