# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/_ipyw_jlab_nb_ext_conf-feedstock/recipe, last modified Thu Sep 21 09:24:34 2017
# ------------------------------------------------

package:
    name: _ipyw_jlab_nb_ext_conf
    version: 0.1.0
build:
    always_include_files:
        - etc/jupyter/jupyter_notebook_config.json
        - etc/jupyter/nbconfig/notebook.json
    number: '0'
    string: py37_0
requirements:
    host:
        - appnope 0.1.0 py37_0
        - backcall 0.1.0 py37_0
        - bleach 2.1.3 py37_0
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - decorator 4.3.0 py37_0
        - entrypoints 0.2.3 py37_2
        - html5lib 1.0.1 py37_0
        - ipykernel 4.8.2 py37_0
        - ipython 6.4.0 py37_1
        - ipython_genutils 0.2.0 py37_0
        - ipywidgets 7.2.1 py37_0
        - jedi 0.12.0 py37_1
        - jinja2 2.10 py37_0
        - jsonschema 2.6.0 py37_0
        - jupyter_client 5.2.3 py37_0
        - jupyter_core 4.4.0 py37_0
        - jupyterlab 0.32.1 py37_0
        - jupyterlab_launcher 0.11.0 py37_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - libsodium 1.0.16 h3efe00b_0
        - markupsafe 1.0 py37h1de35cc_1
        - mistune 0.8.3 py37h1de35cc_1
        - nbconvert 5.3.1 py37_0
        - nbformat 4.4.0 py37_0
        - ncurses 6.1 h0a44026_0
        - notebook 5.5.0 py37_0
        - openssl 1.0.2o h26aff7b_0
        - pandoc 2.2.1 h1a437c5_0
        - pandocfilters 1.4.2 py37_1
        - parso 0.2.1 py37_0
        - pexpect 4.6.0 py37_0
        - pickleshare 0.7.4 py37_0
        - prompt_toolkit 1.0.15 py37_0
        - ptyprocess 0.6.0 py37_0
        - pygments 2.2.0 py37_0
        - python 3.7.0 hc167b69_0
        - python-dateutil 2.7.3 py37_0
        - python.app 2 py37_8
        - pyzmq 17.0.0 py37h1de35cc_3
        - readline 7.0 hc1231fa_4
        - send2trash 1.5.0 py37_0
        - setuptools 39.2.0 py37_0
        - simplegeneric 0.8.1 py37_2
        - six 1.11.0 py37_1
        - sqlite 3.24.0 ha441bb4_0
        - terminado 0.8.1 py37_1
        - testpath 0.3.1 py37_0
        - tk 8.6.7 h35a86e2_3
        - tornado 5.0.2 py37h1de35cc_0
        - traitlets 4.3.2 py37_0
        - wcwidth 0.1.7 py37_0
        - webencodings 0.5.1 py37_1
        - widgetsnbextension 3.2.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zeromq 4.2.5 h378b8a2_0
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - ipywidgets
        - jupyterlab
        - python >=3.7,<3.8.0a0
        - widgetsnbextension
test:
    commands:
        - jupyter-nbextension list
        - jupyter-serverextension list
about:
    home: https://github.com/ContinuumIO/anaconda-nb-extensions-meta-config
    license: BSD
    summary: A configuration metapackage for enabling Anaconda-bundled jupyter extensions
extra:
    copy_test_source_files: true
    final: true
