# This file created by conda-build 3.0.15+5.g16cf4af
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/get_terminal_size-feedstock/recipe, last modified Mon Sep 11 14:04:05 2017
# ------------------------------------------------

package:
    name: get_terminal_size
    version: 1.0.0
build:
    string: h7520d66_0
requirements:
    build:
        - backports 1.0 py36h36758a8_1
        - backports.shutil_get_terminal_size 1.0.0 py36hb6f56af_2
        - ca-certificates 2017.08.26 h1572cdb_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h9485d37_0
        - python 3.6.2 he27cd1a_11
        - readline 7.0 h81b24a6_3
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_0
    run:
        - backports.shutil_get_terminal_size
test:
    imports:
        - backports
        - backports.shutil_get_terminal_size
about:
    description: 'backport of the get_terminal_size function from Python 3.3''s shutil.

        Unlike the original version it is written in pure Python rather than C,

        so it might be a tiny bit slower.

        '
    doc_source_url: https://github.com/chrippa/backports.shutil_get_terminal_size/blob/master/README.rst
    doc_url: https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size
    home: https://github.com/chrippa/backports.shutil_get_terminal_size
    license: MIT
    summary: Get the size of the terminal window.
extra:
    copy_test_source_files: true
    final: true
