# This file created by conda-build 3.8.0
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/6169f73c-233b-4a21-79f3-2dfc03ff1b24/volume/rsync-recipes/dbus-1.13.2-on-osx, last modified Sat Apr 14 05:07:44 2018
# ------------------------------------------------

package:
    name: dbus
    version: 1.13.2
source:
    sha256: 945deb349a7e2999184827c17351c1bf93c6395b9c3ade0c91cad42cb93435b1
    url: http://dbus.freedesktop.org/releases/dbus/dbus-1.13.2.tar.gz
build:
    number: '1'
    run_exports:
        - dbus >=1.13.2,<2.0a0
    string: h760590f_1
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_10
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libiconv 1.15 hdd342a3_7
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - pkg-config 0.29.2 h3efe00b_8
    host:
        - expat 2.2.5 hb8e80ba_0
        - gettext 0.19.8.1 h15daf44_3
        - glib 2.56.1 h35bc53a_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libffi 3.2.1 h475c297_4
        - libiconv 1.15 hdd342a3_7
        - pcre 8.42 h378b8a2_0
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - expat
        - expat >=2.2.5,<3.0a0
        - glib >=2.56.1,<2.57.0a0
test:
    commands:
        - dbus-daemon --version
        - dbus-uuidgen
about:
    description: 'D-Bus is a message bus system, a simple way for applications

        to talk to one another. In addition to interprocess communication, D-Bus helps

        coordinate process lifecycle; it makes it simple and reliable to code a "single

        instance" application or daemon, and to launch applications and daemons on

        demand when their services are needed.

        '
    dev_url: git://anongit.freedesktop.org/dbus/dbus
    doc_source_url: https://cgit.freedesktop.org/dbus/dbus/tree/doc
    doc_url: https://www.freedesktop.org/wiki/IntroductionToDBus/
    home: http://www.freedesktop.org/wiki/Software/dbus/
    license: GPL2
    license_file: COPYING
    summary: Simple message bus system for applications to talk to one another
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - nehaljwani
