# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/appscript-feedstock/recipe, last modified Thu Sep 21 09:24:34 2017
# ------------------------------------------------

package:
    name: appscript
    version: 1.0.1
source:
    md5: 6447b3bef966613bb5ddaedfe32c4558
    url: https://pypi.python.org/packages/source/a/appscript/appscript-1.0.1.tar.gz
build:
    number: '1'
    script: python setup.py install
    string: py37h1de35cc_1
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - aem
        - aem.ae
        - appscript
        - mactypes
        - osax
about:
    description: 'Appscript is a user-friendly Apple event bridge that allows

        users to control scriptable Mac OS X applications from Python, Ruby and Objective-C.

        Appscript makes these languages serious alternatives to Apple''s own AppleScript
        language for automating your Mac.

        '
    doc_source_url: https://sourceforge.net/projects/appscript/?source=navbar
    doc_url: https://pypi.python.org/pypi/appscript
    home: http://appscript.sourceforge.net/
    license: Public-Domain
    summary: Control AppleScriptable applications from Python
extra:
    copy_test_source_files: true
    final: true
