# This file created by conda-build 3.9.1+193.gd10dbde.dirty
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/appnope-feedstock/recipe, last modified Mon Sep 11 14:04:39 2017
# ------------------------------------------------

package:
    name: appnope
    version: 0.1.0
source:
    fn: appnope-0.1.0.tar.gz
    sha256: 8b995ffe925347a2138d7ac0fe77155e4311a0ea6d6da4f5128fe4b3cbe5ed71
    url: https://pypi.io/packages/source/a/appnope/appnope-0.1.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_0
        - openssl 1.0.2o h26aff7b_0
        - python 3.7.0 hc167b69_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.24.0 ha441bb4_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - appnope
about:
    description: 'appnope is a simple package for disabling App Nap on OS X 10.9,
        which can be problematic.

        '
    dev_url: https://github.com/minrk/appnope
    doc_source_url: https://github.com/minrk/appnope/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/appnope/0.1.0
    home: http://github.com/minrk/appnope
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Disable App Nap on OS X 10.9
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
