# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/5f47d4d1-3261-433c-769f-53ae6b34c3a4/volume/rsync-recipes/sortedcontainers-2.1.0-python_3.7-on-osx, last modified Wed Nov 28 17:11:26 2018
# ------------------------------------------------

package:
    name: sortedcontainers
    version: 2.1.0
source:
    fn: sortedcontainers-2.1.0.tar.gz
    sha256: 974e9a32f56b17c1bac2aebd9dcf197f3eb9cd30553c5852a3187ad162e1a03a
    url: https://pypi.io/packages/source/s/sortedcontainers/sortedcontainers-2.1.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20170329 hb402a30_2
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1a h1de35cc_0
        - python 3.7.1 haf84260_3
        - readline 7.0 h1de35cc_5
        - setuptools 40.6.2 py37_0
        - sqlite 3.25.3 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - sortedcontainers
about:
    description: 'SortedContainers is a sorted collections library, written in pure-Python

        and fast as C-extensions.

        '
    dev_url: https://github.com/grantjenks/sorted_containers/
    doc_source_url: https://github.com/grantjenks/sorted_containers/blob/master/docs/index.rst
    doc_url: http://www.grantjenks.com/docs/sortedcontainers/
    home: http://www.grantjenks.com/docs/sortedcontainers/
    license: Apache 2.0
    summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - grantjenks
        - msarahan
        - nehaljwani
        - richafrank
